apple/coremltools

coremltools/models/feature_vectorizer.py
is_valid_feature_list() is called on line 81 but is never defined or imported.  Without this change, NameError might be raised at runtime.
=> Fix is_valid_feature_list() is undefined name

coremltools/models/_graph_visualization.py, coremltools/models/model.py, coremltools/models/neural_network.py, coremltools/models/utils.py, coremltools/test/test_io_types.py, coremltools/test/test_keras2_numeric.py, coremltools/test/test_multiple_images_preprocessing.py, coremltools/test/test_neural_networks.py, coremltools/test/test_numpy_nn_layers.py, coremltools/test/test_recurrent_stress_tests.py, coremltools/test/test_tf_numeric.py
This change allows partial Python 3 support. From Python 3, you should be able to do everything except evaluate models or convert Caffe models. From Python 2, nothing should change.
=> Python 3 Changes

coremltools/test/test_keras2_numeric.py
The strict deltas were causing some nose tests to fail erroneously.
```
1.0 != 0.99887146671109894 within 0.0001 delta
-------------------- >> begin captured stdout << ---------------------
0 : input_19, <keras.engine.topology.InputLayer object at 0x12c3b2090>
1 : dense_57, <keras.layers.core.Dense object at 0x12cd70590>
2 : dense_58, <keras.layers.core.Dense object at 0x12cfc72d0>
...
```
=> Fixed the deltas for the keras2 numeric tests. Deltas were too small.

coremltools/converters/keras/_layers2.py, coremltools/test/test_keras2_numeric.py
This PR: 
(1) add support of ReLU6 layer from mobileNet into Keras converter
(2) revise test_tiny_mobilenet_arch to use relu6
=> Add relu6 support and modify mobilenet nosetests

coremltools/converters/keras/_keras2_converter.py
_KERAS_MERGE_LAYERS is defined in _topology2 which is a conditional import based on _HAS_KERAS2_TF.  Without this change, an NameError might be raised at runtime.
=> Fix _KERAS_MERGE_LAYERS is undefined name

coremltools/models/neural_network.py
The wrong field in the mlmodel protobuf is updated with add_elementwise is called with mode "multiply".
The current implementation updates the field "add" when the correct field should be "mulitply".
This commit fixes this.
=> fix bug add_elementwise with mode multiply

coremltools/converters/keras/_keras2_converter.py
Example of the error message right now:
```
ValueError: Inputimagehas input shape of length4
```
This fixes the spacing and adds quotes around the name to make it more clear:
```
ValueError: Input 'image' has input shape of length 4
```
=> Add missing spaces to error message

coremltools/converters/keras/_keras2_converter.py
I accidentally swapped height and width when the output is 3d blob
=> fix wrong 3d output shape for keras converter

coremltools/models/_graph_visualization.py
CoreML Graph visualization of neural networks shows layers and the parameters associated with it. Some of the parameters are missing or not properly displayed. This PR adds:
- a few more parameters for layer types such as convolution and pooling
- properly displays the enums using string names instead of its index
=> Graph Visualization displaying layer parameters

coremltools/converters/keras/_layers2.py, coremltools/test/test_keras2_numeric.py
This PR:
(1) Fix simpleRNN's removed attribute 'implementation' in most recent Keras version
(2) Fix the delta value for a test running on GPU
=> Fix simpleRNN's removed attribute 'implementation'

coremltools/converters/keras/_layers2.py, coremltools/converters/keras/_topology2.py, coremltools/test/test_keras2_numeric.py
When 1D convolution output is directly fed by flatten layer, Keras converter gives a wrong output shape. 
For example: 
```
input_layer = keras.layers.InputLayer(input_shape=(WINDOW_SIZE, NUM_INPUT_FEATURES), name='input')
encoder_layers = [
keras.layers.AveragePooling1D(2),
Conv1D(16, 1, padding='same', activation='relu', use_bias=False),
keras.layers.MaxPooling1D(2),
Conv1D(16, 1, padding='same', activation='linear', use_bias=False),
keras.layers.MaxPooling1D(pool_size=2)]
classif_layers = [
keras.layers.Flatten(),
Dense(units=7, activation='softmax', use_bias=False)
]
model = keras.models.Sequential([input_layer] + encoder_layers + classif_layers)
import coremltools
coreml_model = coremltools.converters.keras.convert('model.h5')
coreml_model.save('tennis_model.mlmodel')
data = …
```
=> Fixing 1D convolution --> flatten layer bug

coremltools/converters/keras/_topology2.py
This PR adds code to handle list "index out of range" exception when calling `make_output_layers()`. 
The bug is reported in Issue #90, where in `make_output_layers()` there's a call directly to `get_coreml_layers()[0]`  while `get_coreml_layers()` can return an empty list. 
This PR does not, however, identify the cause of `get_coreml_layers()` returning an empty list, which should not be the case for any Keras layer in `model.output_layers`.
=> Index range bug in keras converter function "make_output_layers()"

coremltools/test/test_caffe_stress_tests.py
These tests all take a while and thus marked as slow. All are at least >3min, but several ran for much longer (1+ hour).
The longest ones now are `test_batchnorm` and `test_embed` which both take about 2.5 minutes. I did not mark those as slow.
It looks like a lot of these test many different seeds, so a better solution would be to have a fast version that runs a few seeds and a slow version that runs many more.
=> Mark slow tests as such

coremlpython/CoreMLPythonUtils.mm
- It should check that the value is either int or long (now it checks if value is int or *key* is long)
- It should check that the key is either string or unicode (now it checks if key is string or *the-object-that-we-already-know-is-a-dictionary* is unicode)
I haven't confirmed failure cases, but the former should make things like `{'x': 100L}` fail, and the latter should make things like `{u'x': 100}` fail.
=> Fixes two type checking bugs

coremlpython/CoreMLPythonUtils.mm, coremltools/converters/caffe/_caffe_converter.py, coremltools/models/model.py, coremltools/models/utils.py, coremltools/test/test_caffe_stress_tests.py, coremltools/test/test_keras2.py, coremltools/test/test_multiple_images_preprocessing.py
This gets me passed all non-slow unit tests (with lots skipped - libsvm/xgboost). I will update with comments when I am able to run more tests and confirm they also work.
This PR does not include build configuration for Python 3.
=> Python 3 support for model prediction (+ misc)

mlmodel/src/NeuralNetworkValidator.cpp
LoadConstantLayer's data size calculation in float16 has been forgotted to divided by 2.
=> Fix LoadConstantLayer fp16 data size calculation

coremltools/converters/keras/_topology2.py
Keras ver. 2.1.3 renamed its internal attribute `inbound_nodes` to `_inbound_nodes`, causing keras converter to fail in this version. This PR proposes a simple fix for this version.
=> Fix compatibility issue for keras version 2.1.3

coremltools/test/test_io_types.py
This test is marked as Keras 2 only but still runs (and fails) under Keras 1. This introduces a skipIf to avoid this.
=> Skip Keras 2 only test if user has Keras 1

coremltools/test/test_keras.py, coremltools/test/test_keras_numeric.py
All relevant Keras v1 tests now pass (tested with `Keras==1.2.2`).
=> Fix Keras v1 tests in Python 3

coremltools/converters/xgboost/_tree_ensemble.py
This fixes the following broken test cases under xgboost 0.7 (while still preserving compatibility with older versions):
```
test_boosted_trees_regression_numeric.py::XGboostRegressorBostonHousingNumericTest::test_boston_housing_float_double_corner_case
test_boosted_trees_regression_numeric.py::XGboostRegressorBostonHousingNumericTest::test_boston_housing_parameter_stress_test
test_boosted_trees_regression_numeric.py::XGboostRegressorBostonHousingNumericTest::test_boston_housing_simple_boosted_tree_regression
test_boosted_trees_regression_numeric.py::XGboostRegressorBostonHousingNumericTest::test_boston_housing_simple_decision_tree_regression
test_boosted_trees_regression_numeric.py::XGboostRegressorBostonHousingNumericTest::test_boston_housing_simple_random_forest_regression
```
There …
=> XGBoost 0.7 name change fix

coremltools/models/neural_network.py
The documentation for the LSTM layers claims weights and biases should be `[i, f, z, o]`, but the code treats it as `[i, f, o, z]`.
=> Fix weight ordering in LSTM documentation

coremltools/test/test_recurrent_stress_tests.py
A second round of Keras 2 tests disabled for Keras 1 (this should be it).
- Added `skipIf` whenever there is a mark for keras 2
- Also avoids explicit argument in `reset_states` (API change occurred in
2.0.4 renaming the argument `states_value` to `states`; this is the lowest version that
we support, so it does not affect us, but it also doesn't hurt)
- Removed individual `pytest.mark.keras2` when the whole class is marked
=> More Keras 2 tests that should be disabled for Keras 1

coremltools/_deps/__init__.py, coremltools/test/test_random_forest_classifier_numeric.py
The option `min_impurity_decrease` was introduced in scikit-learn 0.19, so this checks if that setting is available. With this, the test passes with both pre and post that release.
A simpler solution is just take out `min_impurity_decrease` altogether as long as we support earlier versions than 0.19.
=> Handle API change in scikit-learn 0.19 for tests

README.md
I'm proposing bumping some versions of dependencies in the README, for the following reasons:
XGBoost v0.6 can't export to JSON, which the converter depends on.
Coremltools previously depended on an unreleased v0.6+ version, but
now that v0.7 is released, let's bump this.
Scikit-learn: Many tests (22+) are broken on 0.15 and 0.16, so
this bump is simply a reflection of reality.
=> Bump dependency on scikit-learn and xgboost (based on extensive testing)

coremltools/converters/libsvm/_libsvm_converter.py, coremltools/converters/sklearn/_svm_common.py, coremltools/models/datatypes.py, coremltools/models/neural_network.py, coremltools/test/test_model.py, coremltools/test/test_neural_networks.py
This is a fix for Python 3, while on Python 2 the `b` prefix is a no-op.
Protobuf on macOS never had this issue, so this is a fix for Linux.
=> Protobuf (on Linux) requires bytes objects

coremltools/test/test_recurrent_stress_tests.py, coremltools/test/test_simple_recurrent_single_layer.py
This PR makes sure that:
* the RNN tests all pass (on Keras 1 and 2)
* has slow/fast versions
* relevant tests have both keras1/keras2 versions (sometimes only one was available and occasionally it was marked as keras2 but used the keras1 API).
It does not:
* Address test redundancy. For instance, there seems to be multiple tests addressing the same converter, but are slightly different in terms of parameter coverage. For instance, `SimpleRNNLayer` is tested with similar testing infrastructure in:
* `test_simple_recurrent_single_layer.py::SimpleRNNLayer`
* `test_recurrent_stress_tests.py::SimpleTestCase`
* `test_recurrent_stress_tests.py::RNNLayer`
* On that note, the distinction between `test_recurrent_stress_tests.py` and `test_simple_recurrent_single_layer.py` is unclear and can …
=> Clean-up and fix failed tests for RNNs

coremltools/test/test_simple_recurrent_single_layer.py
I only tested the last PR on Python 3, where this is fine, so this syntax error in Python 2 snuck in.
=> Fix Python 2 syntax error

CMakeLists.txt, README.md, README.rst, coremltools/_deps/__init__.py, coremltools/test/test_multiple_images_preprocessing.py, docker/Dockerfile-python2.7-build, docker/Dockerfile-python2.7-test, docker/Dockerfile-python3.5-build, docker/Dockerfile-python3.5-test, docker/Dockerfile-python3.6-build, docker/Dockerfile-python3.6-test, docs/conf.py, setup.py, test_requirements.pip
* Tweak CMakeLists.txt to work with multiple Python versions on the same
machine (using env variables to distinguish).
* Allow tests to run without CAFFE_MODELS_PATH env variable set.
* Add test_requirements.pip to pin specific versions of dependent
packages used in testing.
* Add Dockerfiles to denote a consistent and reproducable environment
for building and testing releases.
=> Prepare 0.8 release

CMakeLists.txt
Building using `python-config` from a Python.org download of Python
results in /Library/Frameworks instead of /System/Library/Frameworks;
this path needs to be taken into account to work on other Python
distributions.
=> Fix rpath with Python in /Library/Frameworks

CMakeLists.txt
* Look in the local virtualenv for rpath first (may contain a libpython
dylib).
* If local virtualenv doesn't contain a dylib, look in
/Library/Frameworks
With the previous rpath fixes, this seems to work on system Python,
Python from Python.org, and other distributions.
=> More @rpath fixes

docker/Dockerfile-python2.7-build, docker/Dockerfile-python2.7-test, docker/Dockerfile-python3.5-build, docker/Dockerfile-python3.5-test, docker/Dockerfile-python3.6-build, docker/Dockerfile-python3.6-test
* vim-common for some reason provides `config`, needed for
`python-config`.
* bzip2-devel is needed to `import bz2` in Python; may be useful for
manual testing.
* On CentOS 7, `which` is not provided by default.
=> Add some useful utilities for debugging builds

docker/Dockerfile-python2.7-build, docker/Dockerfile-python2.7-test, docker/Dockerfile-python3.5-build, docker/Dockerfile-python3.5-test, docker/Dockerfile-python3.6-build, docker/Dockerfile-python3.6-test
This fixes `import sqlite3` in Python; without compatible
dependencies and build flags, Python excludes this capability by
default.
See https://stackoverflow.com/questions/1210664/no-module-named-sqlite3
=> Enable Python sqlite module

CMakeLists.txt
Turns out the best way to obtain compatibility across Python
distributions, it seems, is to not link libpython*.dylib at all! If we
instruct the linker not to worry about undefined symbols, it turns out
the symbols will all come from the running Python process at import
time, and it works across a variety of Python distributions.
=> Fix PyThreadState_Get errors

README.md, README.rst, setup.py
Tested across a variety of Python distributions and versions; 1.10.0
seems to be the minimum version that is API- and ABI-compatible with
current versions of numpy for our purposes.
=> Bump min numpy version to 1.10.0

coremltools/converters/keras/_topology2.py, coremltools/test/test_keras2_numeric.py
Keras converter fails when a top-level model contains a nested model, and the top-level model's output layer is within the nested model. 
This PR fixes this issue.
=> Fix bugs for keras models with outputs coming from nested models

coremltools/converters/keras/_layers2.py, coremltools/test/test_keras2.py, coremltools/test/test_keras2_numeric.py
Issue with Keras SeparableConv2D layer conversion fixed: added dilations to intermediate depthwise convolution.
Issue example (road scene segmentation):
1. Raw image
2. Predicted segmentation mask on PC (model trained with Keras 2.1.3 and TensorFlow-1.5.0 backend, CUDA 9.0):
3. Predicted segmentation mask on iPhone X (same model, converted with coremltools-0.8):
After fixing "convert_separable_convolution" method predicted segmentation mask on device corresponds to predicted mask on PC:
=> SeparableConv2D: dilations issue fixed

CMakeLists.txt
It's been an issue for a while that you sometimes need to add the numpy include path manually (especially if you are on python 3). @aseemw just encountered this recently, so I figured it was finally time to fix this.
=> Fetch numpy include path from np.get_include() in CMakeLists.txt

coremltools/graph_visualization/app.js, coremltools/graph_visualization/index.html, coremltools/models/_graph_visualization.py, coremltools/models/model.py, coremltools/models/utils.py, docs/index.rst
1. Added deconvolution and global pooling as layer types
2. Added documentation for visualization
3. removed visualization from utils and added to model class for making it easier to call using model.visualize()
4. Minor polish on UI
5. Gave user option to provide input shape for Sequence, Batch > 1
=> Bug fixes and improvements to the core ml visualization tool

coremltools/converters/keras/_topology2.py, coremltools/test/test_keras2.py
When a Keras model contains SeparableConv1D or SeparableConv2D with some nonlinearity, the corresponding activation layer in CoreML model graph is not present. As a result, the converted model is broken.
This pull request contains the fix.
=> Fix: Keras converter is dropping out fused activation layers for SeparableConv1D and SeparableConv2D

mlmodel/src/NeuralNetworkValidator.cpp
gcc7+ seems stricter than previous releases, and now requires
`<functional>` to be included in order to use `std::function`.
See also apple/turicreate#1122
=> Fix a build break in gcc7

coremltools/converters/keras/_layers2.py
Keras 2.2.2 doesn't have keras_applications.mobilenet.relu6 anymore, resulting in an ImportError if code is run with this and posterior versions. This PR checks for the appropriate Keras version and provides a dummy replacement for relu6.
=> Update imports for relu6 removal in Keras 2.2.2

coremltools/converters/keras/_keras2_converter.py, coremltools/converters/keras/_layers2.py, coremltools/test/test_keras2_numeric.py
In ver==2.2.1 Keras removed ReLU6 under keras_application.mobilenet
and replaced with a general ReLU with max value, which caused
issues to the Keras converter. This commit fixes this issue.
=> Resolve Keras ver>=2.2.1 ReLU issues

mlmodel/src/NeuralNetworkValidator.cpp, mlmodel/src/NonMaximumSuppressionValidator.cpp, mlmodel/src/QuantizationValidationUtils.cpp, mlmodel/src/QuantizationValidationUtils.hpp, mlmodel/src/ValidatorUtils-inl.hpp
- For compatibility with pre-C++14, don't use auto in lambda arguments
- To avoid a warning, use parentheses to make explicit the precedence of && over ||
- QuantizationValidationUtil.{hpp,cpp} can #include only files inside the MLModel directory (the portion dropped into Turi Create)
- ValidatorUtils-inl.hpp should include Result.hpp instead of relying on its clients to include Result.hpp first
=> Fixes to facilitate source drops into Turi Create

CMakeLists.txt, mlmodel/build/format/ArrayFeatureExtractor_enums.h, mlmodel/build/format/BayesianProbitRegressor_enums.h, mlmodel/build/format/CategoricalMapping_enums.h, mlmodel/build/format/CustomModel_enums.h, mlmodel/build/format/DataStructures_enums.h, mlmodel/build/format/DictVectorizer_enums.h, mlmodel/build/format/FeatureTypes_enums.h, mlmodel/build/format/FeatureVectorizer_enums.h, mlmodel/build/format/GLMClassifier_enums.h, mlmodel/build/format/GLMRegressor_enums.h, mlmodel/build/format/Identity_enums.h, mlmodel/build/format/Imputer_enums.h, mlmodel/build/format/Model_enums.h, mlmodel/build/format/NeuralNetwork_enums.h, mlmodel/build/format/NonMaximumSuppression_enums.h, mlmodel/build/format/Normalizer_enums.h, mlmodel/build/format/OneHotEncoder_enums.h, mlmodel/build/format/SVM_enums.h, mlmodel/build/format/Scaler_enums.h, mlmodel/build/format/TextClassifier_enums.h, mlmodel/build/format/TreeEnsemble_enums.h, mlmodel/build/format/VisionFeaturePrint_enums.h, mlmodel/build/format/WordTagger_enums.h, mlmodel/tools/enumgen.cpp
Instead of #pragma clang warning suppression. The attribute syntax works
across compiler toolchains (clang/gcc/etc.).
=> Switch to __attribute__((__unused__))

docs_requirements.txt, mlmodel/Requirements.txt
It doesn't appear to be used anywhere, and the specific versions
requested are now unsupported and have reported vulnerabilities.
=> Drop requests dependency

coremltools/models/neural_network/flexible_shape_utils.py
I changed the function names rather than the keys for `self.arrayShapeRange` because I want to keep the C,H,W orders consistent.
=> Incorrect keys for get_{width/height}_range in flexible_shape_utils

coremltools/converters/keras/_layers2.py, coremltools/test/test_keras2.py
In newer Keras there is a support for bilinear interpolation.
This PR adds a logic to handle it properly.
=> Support for bilinear interpolation for upsampling Keras layer

coremltools/converters/keras/_layers2.py
This is a follow-up for #343 .
Pull request contained a bug which caused AttributeError exception for early Keras versions.
=> Fix AttributeError exception bug for PR #343

docs_requirements.txt, mlmodel/Requirements.txt
It isn't being used anywhere; only listed in these two requirements
files.
=> Remove jinja2

mlmodel/build/format/CategoricalMapping_enums.h, mlmodel/build/format/CustomModel_enums.h, mlmodel/build/format/DictVectorizer_enums.h, mlmodel/build/format/FeatureTypes_enums.h, mlmodel/build/format/GLMClassifier_enums.h, mlmodel/build/format/Imputer_enums.h, mlmodel/build/format/Model_enums.h, mlmodel/build/format/NeuralNetwork_enums.h, mlmodel/build/format/NonMaximumSuppression_enums.h, mlmodel/build/format/OneHotEncoder_enums.h, mlmodel/build/format/SVM_enums.h, mlmodel/build/format/TextClassifier_enums.h, mlmodel/build/format/TreeEnsemble_enums.h, mlmodel/build/format/VisionFeaturePrint_enums.h, mlmodel/build/format/WordTagger_enums.h, mlmodel/tools/enumgen.cpp
The generated code in enums gives warnings (including warning-as-error)
in GCC 4.8, which also can't be suppressed via pragma GCC diagnostic.
The workaround here is to add an explicit return statement past the
switch statement, so the compiler thinks we are always returning
something (even though we always were anyway).
=> In GCC 4.8, -Wreturn fails on exhaustive switch

coremltools/converters/keras/_topology2.py
Keras layers may contain "dummy" inbound nodes that are empty.
This causes converter to mistakenly treat it as a shared layer and
fail subsequently.
This PR fix this problem by filtering out the dummy inbound nodes.
=> Keras layers may contain dummy inbound nodes which do not

coremltools/converters/nnssa/coreml/shapes.py, coremltools/converters/nnssa/coreml/ssa_converter.py, coremltools/converters/nnssa/frontend/graph_pass/type_inference.py
New Conversion functions:
- Slice
- SelectMask
- FloorMod
- ReverseSequence
- Squeeze
- Elu
- GreaterEqual
Modified/fixed issues in conversion functions for:
- Maximum (included broadcasting support)
- Minumum (included broadcasting support)
- Cast (changed from identity to round)
and corresponding shape propagation for each these layers. 
Fixed shape propagation for all broadcast able ops.
=> Adding coversion functions for multiple layers along with shape propagation logic & fixing multple bugs

coremltools/models/_infer_shapes_nn_mlmodel.py
axis = list(map(int, params.axis))
In python3, for _permute(), 'map' object is not subscriptable.
Map object is passed to a list.
=> Map object not subscriptable

README.md
* 'Tensorflow' -> 'TensorFlow'
* 'Scikit Learn'  -> 'scikit-learn'
* 'CoreMLTools' -> 'coremltools'
* 'Xgboost' -> 'XGBoost'
This is a follow-up to #418.
=> [README] More spelling corrections.

coremlpython/CoreMLPythonUtils.mm
CoreMLPythonUtils.mm:convertValueToImage leaks a CVPixelBuffer
Add the missing CVPixelBufferRelease()
=> Fix CoreMLPythonUtils.mm:convertValueToImage leaks

coremltools/converters/nnssa/coreml/graph_pass/op_fusions.py, coremltools/converters/nnssa/coreml/shapes.py, coremltools/converters/nnssa/coreml/ssa_converter.py, coremltools/converters/nnssa/frontend/graph_pass/type_inference.py, coremltools/converters/nnssa/frontend/tensorflow/graph_pass/fusedbatchnorm_rewrite.py, coremltools/converters/nnssa/frontend/tensorflow/load.py, coremltools/converters/tensorflow/test/test_convnets.py
(1) adds depthwise convolution conversion
(2) make sure mobile net conversion passes for V1 and V2
(3) re-implement type-inference for Conv2D and DepthwiseCovn2dNative
(4) fix NHWC-NCHW transforms for ReLU6 and DepthwiseConv2dNative
(5) fix numerical instability cause by ignored epsilon in fusing FusedBatchNorm
(6) adds unit test for conv->batchnorm
=> Adds conversion functions to support MobileNetV1/V2

coremltools/converters/nnssa/coreml/ssa_converter.py, coremltools/converters/tensorflow/test/test_base.py, coremltools/converters/tensorflow/test/test_tf_graphs.py
This change makes buffers on the input and output ports of CoreML RNN
layers. This can avoid generating CoreML models with undefined number
of state updates of RNN.
=> Buffer input and output states for converting CoreML RNN layers

coremltools/models/_infer_shapes_nn_mlmodel.py
It seems that type(layer_type) will always be 'str'. And the error message should include the name of the layer (the content of layer_type), rather than 'str'.
=> Fixing error message in _get_translator_function

coremltools/converters/nnssa/coreml/graph_pass/__init__.py, coremltools/converters/nnssa/coreml/graph_pass/op_fusions.py, coremltools/converters/nnssa/coreml/graph_pass/op_removals.py, coremltools/converters/nnssa/coreml/shapes.py, coremltools/converters/nnssa/coreml/ssa_converter.py, coremltools/converters/nnssa/frontend/graph_pass/type_inference.py
This PR:
(1) Add a graph pass to remove dummy split layer
(2) Fix bug in nnssa type inference in strided-slice
(3) Add conversion function to ResizeNearestNeighbor when target size is smaller than input size
(4) Remove transposes around DepthToSpace/SpaceToDepth conversion
(5) Allow conversion to proceed with unsupported symmetric mirror pad and give a warning
=> Bug fixes for image downsize, one-way split, slice, and depth-to-space

docs/NeuralNetworkGuide.md
Add a link to the gpt2 script in the hugging face repo, as an example of building a CoreML model from scratch using the builder APIs.
=> Add a link to builder API example

coremltools/converters/nnssa/coreml/ssa_converter.py, coremltools/models/neural_network/builder.py, coremltools/test/neural_network/test_neural_networks.py
I cannot convert simple network with `image_input_names = ...` (i.e., classifier) and `class_labels = FILENAME` without these two one-line patches.
what I used to convert TensorFlow frozen pb is something like:
```python
model = tf_converter.convert(tf_model_path = 'mobilenet_v2_1.0_224.pb',
mlmodel_path = 'MobileNetV2.mlmodel',
image_input_names = ['input'],
input_name_shape_dict = {'input' : [1, 224, 224, 3]},
output_feature_names = ['MobilenetV2/Predictions/Softmax'],
class_labels = 'labels.txt',
predicted_feature_name = 'classLabel',
predicted_probabilities_output = 'classLabelProbs',
red_bias = -1,
green_bias = -1,
blue_bias = -1,
image_scale = 2.0/255.0,
target_ios='13')
```
=> Fix two trivial bugs when `target_ios='13'`

coremltools/test/neural_network/test_neural_networks.py
Removing `/tmp/` data after test #579
=> Removing  data after test #579

coremltools/test/xgboost/test_boosted_trees_regression_numeric.py
Marked a flaky XGboost regression test as a known failure which causes some failures on Mac.
=> Marking XGboost test as xFail 

BUILD.md, CMakeLists.txt, configure
This adds support for out of tree builds.
Existing definitions were conflicted about expected and also not
allowing source and build directories to be identical, so POST_BUILD
hooks did not resolve.
=> Automate initial build and testing steps via CMake

coremltools/converters/nnssa/coreml/graph_pass/mlmodel_passes.py, coremltools/converters/nnssa/coreml/ssa_converter.py, coremltools/converters/tensorflow/test/test_tf_2x.py, coremltools/models/neural_network/builder.py, coremltools/test/neural_network/test_graph_passes.py
Conv2D layers have a transpose inserted before them to swap `NHWC` -> `NCHW`. If the input image format in the original TF model is `NHWC`, a transpose at the input from `NCHW` -> `NHWC` is added. If these layers are next to each other, the pair of transposes are redundant. This fix adds a pass in the mlmodel conversion to find and remove these kind of redundant transpose pairs.
Fixes #591.
=> Fix redundant transpose ops.

coremltools/converters/tensorflow/test/test_tf_2x.py
Switch test to use layer type rather than name - name changes depending on quantity and ordering of tests.
=> test should use layer name

.gitlab-ci.yml
The artifact from the linux python 3.7 wasn't in the list.
=> Collect artifacts from the newly minted python 3.7 linux target

coremltools/converters/nnssa/coreml/ssa_converter.py, coremltools/converters/tensorflow/_tf_converter.py, coremltools/test/neural_network/test_neural_networks.py
Add image_format parameter to TensorFlow converter to allow callers to manually specify NCHW or NHWC format, if needed.
=> Add image_format parameter to TensorFlow converter

coremltools/converters/tensorflow/test/test_tf_2x.py
There is no unit test class for a single tf2 op now,
so I just added the test case,
in order to add further tf2 op test (like AddN and Einsum ... ).
=> add tf2 single op unit test (without calling keras).

examples/NeuralNetworkGuide.md
The link to the `coremltools` model quantization examples is dead in the docs of this repo. This PR fixes the link to point to the new location: https://github.com/apple/coremltools/blob/master/examples/APIExamples.md#quantizing-a-neural-network-mlmodel
=> Update link to coremltools model quantization docs

coremltools/models/model.py
This allows both of the following: 
`m = coremltools.models.MLModel('~/Downloads/VGGishInt8.mlmodel')`                                                     `m.save('~/tmp/fooo33o.mlmodel')`.
Also fixes some import statements.
=> Allow tilda in paths

examples/neural_network_inference/Neural_network_control_flow_power_iteration.ipynb
Fix invocation of the builder API for the reduce layer which now expects `axes` attribute to be a list
=> Fix typo in jupyter notebook example

coremltools/converters/nnssa/coreml/ssa_converter.py, coremltools/converters/tensorflow/test/test_convnets.py
When the conversion of `Sub` operation's second input value is zero, the following error occurred. I fix the error by replacing to `is not None` check.
<details>
<summary>log</summary>
<div markdown="1">
```
Traceback (most recent call last):
File "/Users/doyounggwak/Project/ml-project/github/tf2-mobile-pose-estimation/tmp.py", line 80, in <module>
outputs=[output_name]
File "/Users/doyounggwak/anaconda3/envs/pose_tf2_env/lib/python3.6/site-packages/coremltools/converters/tensorflow/_tf_converter.py", line 193, in convert
optional_inputs=optional_inputs)
File "/Users/doyounggwak/anaconda3/envs/pose_tf2_env/lib/python3.6/site-packages/coremltools/converters/nnssa/coreml/ssa_converter.py", line 154, in ssa_convert
converter.convert()
File …
```
=> Fix alpha check to checking not None on ssa_converter.py

examples/NeuralNetworkGuide.md
This PR updates several of the example links to point to the correct repository (previously pointed to `tf-coreml` repo
=> Update examples links to point to coremltools repo

coremltools/converters/sklearn/_imputer.py
As of scikit-learn >= 0.21, the `Imputer` class no longer exists. I've addressed it in the same way as they've done [here](https://github.com/onnx/onnxmltools/pull/313/files), with a try-catch import. I'm really not a domain expert here, so I'm happy for other suggestions on how to resolve. 
Otherwise, with the current version of mltools running against scikit-learn >= 0.21, we'll get something like this when running `coreml_model = coremltools.converters.sklearn.convert(classifier)` : 
```
Traceback (most recent call last):
File "my-script.py", line 68, in <module>
main()
File "my-script.py", line 61, in main
coreml_model = coremltools.converters.sklearn.convert(classifier)
File "/usr/local/lib/python3.7/site-packages/coremltools/converters/sklearn/_converter.py", line 145, in convert …
```
=> support scikit-learn >= 0.21

coremltools/__init__.py, coremltools/test/neural_network/test_graph_passes.py, coremltools/test/sklearn/test_utils.py
Also disable `Redundant_Transposees_Test` tests on mac os lower than 10.15, since they use the transpose layer that was added in 10.15.
=> Update version to 3.4

coremltools/converters/nnssa/coreml/graph_pass/op_fusions.py
"enumerate" does not copy the argument.
=> bugfix: needs to copy a list since the original is changed inside loop

coremltools/models/neural_network/optimization_utils.py
When I tried to quantize a model which has the batch normalization layers, in spite of not having scale layers, `_fuse_layer_with_scale_layer()` is called, and this process failed in the process of the model optimization.
if `bn_layers.append(bn_layer_idx)` is processed, it appends `bn_layer_idx` to `conv_layers`, `ip_layers`, `bias_layers` and `scale_layers`.
So I changed the line 175 in `optimization_utils.py`, the model quantization was succeeded.
=> Fixed the initialization list of the layer types in _optimize_nn()

coremltools/converters/mil/frontend/tensorflow/ops.py
I had trouble converting Tensorflow 2 UpSampling2D layer when using bilinear mode, because in coremltools/converters/mil/frontend/tensorflow/ops.py, the ResizeBilinear function asserts that the output sizes must be in int32. This allows ResizeBilinear function to also allow output sizes to be in int64. This also makes ResizeBilinear consistent with  ResizeNearestNeighbor.
=> ops ResizeBilinear to also accept output size in int64

.gitlab-ci.yml
Run CI based on file touched.
In total, we have 5 test suites:
- MIL ops
- PyTorch ops
- TF1 ops
- TF2 ops
- coremltools/test
with `only:changes:`, we trigger the corresponding test based on files touched. @DawerG Can you help to double-check those conditions. Thanks!
=> CI: run tests based on files touched

scripts/sync_gitlab_with_github.py, scripts/sync_gitlab_with_github.sh
The current CI setup only seems to kick off builds for commits that have
been pushed to either a branch on apple/coremltools on GitHub, or a
branch on zach_nation/coremltools on Gitlab. This script will enumerate
all of the open PRs on GitHub apple/coremltools, and push their commits
to a corresponding branch on zach_nation/coremltools.
Requires a valid GitHub access token to be set as an environment
variable. This is to use the GitHub API, but it doesn't need any access
beyond PRs on public repos.
Requires push access to zach_nation/coremltools. Only zach_nation can
give you this.
=> Add a script to sync PRs to Gitlab for CI

docker/Dockerfile-sync-gitlab-with-github, scripts/sync_gitlab_with_github.py, scripts/sync_gitlab_with_github.sh
* Use a Docker container with minimal dependencies, based on python:3.7.
* Remove the dependency on local env (in CI this will take quite a while
to create on each run).
* Also fixed a bug: when multiple PRs share the same origin, don't try
to add it twice to our list of remotes.
=> Speed up execution of sync_gitlab_with_github.sh

.gitlab-ci.yml
* Adds a new CI job, sync_gitlab_with_github, to run the corresponding
script. This is intended to be used on a schedule and will only run on
scheduled pipelines.
* Tells all other jobs to _not_ run on scheduled pipelines, so we can
have a totally separate CI job that just updates Gitlab on a schedule
without building the rest of the repo.
=> Enable scheduled CI job to sync Gitlab CI

.gitlab-ci.yml
Instead of relying on the Gitlab CI credentials (which don't have push
permission), see if we can get the credentials from environment
variables and insert them into the current SSH config.
=> Try to get SSH keypair for sync from env variable

README.md
Now that we're using Gitlab builds for PRs and master, the status badge should reflect that build.
=> Update build status badge to point to Gitlab

coremltools/converters/mil/frontend/torch/ops.py
As discussed in issue #823, this should fix #823  and is based on #759.
These 4 lines were seemingly dropped in the beta2 merge. 
Also added a .any() in L1532. 
There is a testcase to check in #823 to verify that all variants are good.
=> Update ops.py to Fix #823

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
This PR adds support for converting PyTorch 2-D adaptive max pooling layers.
`coremltools` already has support for 2-D adaptive average pooling layers. This commit is strictly based off of that existing implementation, except that it builds with the operations `reduce_max` and `max_pool` instead of `reduce_mean` and `avg_pool`.
Why do max pooling layers matter? Besides the fact that they are part of PyTorch, they are frequently used in models produced by the [FastAI library](https://github.com/fastai/fastai), so `coremltools` will be better able to convert those models if it adds support for this layer type.
I am not sure what is official process for contributing a PR, so I would be glad to receive any guidance on what other steps might be necessary in order to improve this change as …
=> Add support for torch layer adaptive_max_pool2d

coremltools/converters/mil/mil/ops/defs/linear.py
Edit the docstrings to create the documentation for the [converter.mil.ops](https://coremltools.readme.io/reference/convertersmilops) page for the following ops:
linear
matmul
tbove@apple.com
=> Docs: Add converter.mil.ops documentation for linear.py

coremltools/converters/mil/mil/ops/defs/normalization.py, docs/MIL/coremltools.converters.mil.ops.rst
The HTML file wasn't building correctly due to the op doc index being out of date.
One of the comments contained special unicode characters that couldn't be uploaded.
=> Fix documentation errors

coremltools/converters/mil/mil/ops/defs/linear.py
Fixes spelling "NumPy", "1-D" and other errors, and updates the formatting.
=> Docs: Update converter.mil.ops documentation for linear.py

coremltools/converters/mil/mil/ops/defs/linear.py
Quick fixes to spacing in the docstrings in linear.py (MIL ops `linear` and `matmul`).
=> Docs: Fix spacing in converter.mil.ops doc

coremltools/converters/mil/mil/ops/defs/linear.py
Fixed the doc formatting for the linear and matmul ops in converter.mil.ops page. 
Preview of this page is here: [converter.mil.ops preview](https://coremltools.readme.io/v1.0/reference/convertersmilops)
See "matmul" and "linear" ops.
=> Docs: Fix doc formatting for linear and matmul (linear.py)

coremltools/converters/mil/input_types.py
Make me happy and accept this `__repr__` for RangeDim (with `__str__ = __repr__`). Something so basic surely deserves either this implementation or something you'd think fits.
Thanks!
Example `__repr__`:
```
>>> from coremltools.converters.mil.input_types import RangeDim
>>> RangeDim(1,2)
RangeDim(1, 2, 1, "is0")
```
=> __repr__,__str__ for RangeDim

coremltools/converters/mil/mil/ops/defs/normalization.py
Fix formatting for MIL ops in normalization.py for [converter.mil.ops](https://coremltools.readme.io/reference/convertersmilops). Ops are:
batch_norm, instance_norm, l2_norm, layer_norm, and local_response_norm. 
=> DOCS: Update mil ops in  normalization.py for converter.mil.op

coremltools/converters/mil/mil/ops/defs/activation.py
Includes changes to the docstrings for the following MIL ops (includes formatted math formulas for `gelu`):
```
clamped_relu
elu
gelu -- see formulas
leaky_relu
linear_activation
prelu
relu
relu6
scaled_tanh
sigmoid
sigmoid_hard
softplus
softplus_parametric
softmax
softsign
thresholded_relu
```
=> Docs: Fix doc formatting for activation.py in converter.mil.ops

coremltools/converters/mil/mil/ops/defs/normalization.py
Adds formulas and makes changes to the docstrings for the following MIL ops:
```
batch_norm
instance_norm
l2_norm
layer_norm
local_response_norm
```
=> Docs: Add formulas for normalization.py in converter.mil.ops

coremltools/converters/mil/mil/ops/defs/control_flow.py
This PR completes the work that was formerly in [PR 916](https://github.com/apple/coremltools/pull/916).
Includes changes to the docstrings for the following MIL ops:
```
cond
const
select
while_loop
make_list
list_length
list_write
list_read
list_gather
list_scatter
```
=> Docs: Fix formatting for control_flow.py in converter.mil.ops

coremltools/converters/mil/mil/ops/defs/normalization.py
Fixes the formula for the `batch_norm` MIL ops. (The previous PR
was merged before this fix was applied.)
=> Docs: Fix formula in normalization.py in converter.mil.ops

coremltools/converters/mil/mil/ops/defs/control_flow.py
Fixes the mistaken edit "It must take ``0`` as input" to be
"It should take no input". This appears twice.
=> Docs: Fix phrases in control_flow.py in converter.mil.ops

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Hi! Thanks for open-sourcing the framework! This fixes transposed convolution for 1D/3D cases in PyTorch (#904).
=> Fix PyTorch transposed convolution

mlmodel/src/Validation/NeuralNetwork/NeuralNetworkValidator.cpp
Hi.
coremltools and Xcode output confusing error message for some inconsistent model, which describes a layer's input as output.
This pull request fixes it.
=> fixed confusing error message

coremltools/converters/mil/frontend/torch/ops.py
A simple torch `copy_` op implemented using `mb.identity`
=> Add copy_ torch op from #918

coremltools/converters/onnx/_converter.py
Before this change, hitting this error would look like this
```
TypeError: ('{} not supported. Please provide one of target iOS: {}', 14, ['11.2', '12', '13'])
```
Now it looks as intended:
```
TypeError: 14 not supported. Please provide one of target iOS: ['11.2', '12', '13']
```
=> add missing format call

.gitlab-ci.yml
- Removes Python 2.7 from building and testing in the CI.
=> Remove Python 2.7 from gitlab CI

coremltools/converters/onnx/_operators_nd.py
Currently the onnx converter ignores the `k` argument for the `topk` layer, this PR fixes it.
=> fixed topk export ignoring constant k

coremltools/converters/mil/backend/nn/load.py, coremltools/converters/mil/mil/passes/image_input_preprocessing.py, coremltools/test/api/test_api_examples.py, reqs/test.pip
This has more fixes on top of the fixes made in #996 , to make sure that enumerated image inputs work with pre-processing parameters, and enumerated shapes are not repeated. 
Also updates the tests.
=> More fixes to make enumerated image inputs work correctly

coremltools/converters/mil/frontend/tensorflow/load.py, coremltools/converters/mil/frontend/tensorflow/tf_graph_pass/constant_propagation.py
The check `tf.__version__ < _StrictVersion("1.13.1")` fails, when TF is an `rc` version, e.g.: `2.4.0rc2`, since `distutils.version.StrictVersion` does not work properly with release candidate versions (a known issue with StrictVersion). 
This PR updates this check to first clean up the version using the method `coremltools._deps.__version` after which comparison with StrictVersion can be safely done. 
Fixes #1001
=> Update version check

coremltools/__init__.py
Pull request proposal for solving a _minor_ issue of logging outputting.
The following code can be used in order to reproduce the mentioned issue:
```
import coremltools
import logging
FORMAT = '%(asctime)-15s - %(levelname)s - %(message)s'
logging.basicConfig(format=FORMAT, level=logging.INFO)
logger = logging.getLogger()
logger.info("This message does not show up unless the coremltools import above is removed.")
```
I suspect that the issue might be related to one of the dependencies used by coremltools, not sure which one. But the thing is that the root logger is being modified whenever coremltools is imported and normally that's not a good practice as far as I know.
Anyway, it is a minor issue because it can be avoided disabling logging propagation, removing the root logger handlers, …
=> Added root logger isolation

coremltools/converters/mil/frontend/tensorflow/__init__.py
Please consider this quick proposal of adding an environment variable (flag) in order to externally have the possibility of bypassing the TensorFlow log suppression. Otherwise, this log suppression would have to be reverted every time that this module is imported; so this flag would ease things up.
A conservative default value has been added in order to assure the backward compatibility of these minor changes.
Many thanks for your time.
=> Added flag for bypassing TensorFlow log suppression

reqs/test.pip, scripts/build_docs.sh
The installation step of test.pip fails due to strict checking by pip 20.3
This PR fixes those issues by updating the torch and torchvision packages and putting minimum versions for a few other packages to avoid pypi backtracking. 
Pytorch 1.7 will be supported after the fixes proposed in #1020 and #1027. This PR unblocks the CI testing of those PRs.
=> Fix CI test build issues

coremltools/converters/mil/frontend/torch/ops.py
Hi, 
This is less of a bugfix and more of a "better safe than sorry" change. In PyTorch you can set the default tensor type to be `torch.cuda.FloatTensor`, which resides on gpu. In this case when you call `torch.tensor` you get a gpu tensor back, and the `.numpy()` call fails. So if you have something like this the following snippet conversion would fail
`import torch`
`torch.set_default_tensor_type('torch.cuda.FloatTensor')`
`print(torch.tensor(1).device)`
`... do the actual coreml conversion...`
There's a few other locations (tests) that use `torch.tensor`, however I don't think any final user touches these, so left them as they are.
=> Make sure torch.tensor returns a cpu tensor

coremltools/converters/mil/frontend/torch/converter.py, coremltools/converters/mil/frontend/torch/ops.py
For PyTorch 1.7.0, the `convolution` ops takes 13 inputs. The newly added one is `allow_tf32`, which is a flag to enable TensorFloat32 (TF32) tensor cores on new NVIDIA GPUs since Ampere. So I changed the `len(inputs) == 12` to `len(inputs) >= 12` to prevent the `unexpected number of inputs for node` exception.
Ref: https://pytorch.org/docs/stable/notes/cuda.html#tensorfloat-32-tf32-on-ampere-devices
=> Fix number of inputs for convolution torch ops

README.md
add link of the latest CI run on master, to the build badge in readme, for easy access
=> Link in build badge to CI run

coremltools/converters/_converters_entry.py, coremltools/converters/caffe/_caffe_converter.py, coremltools/converters/mil/mil/ops/defs/activation.py, coremltools/converters/mil/mil/ops/defs/control_flow.py, coremltools/converters/mil/mil/ops/defs/conv.py, coremltools/converters/mil/mil/ops/defs/elementwise_binary.py, coremltools/converters/mil/mil/ops/defs/elementwise_unary.py, coremltools/converters/mil/mil/ops/defs/image_resizing.py, coremltools/converters/mil/mil/ops/defs/linear.py, coremltools/converters/mil/mil/ops/defs/normalization.py, coremltools/converters/mil/mil/ops/defs/pool.py, coremltools/converters/mil/mil/ops/defs/random.py, coremltools/converters/mil/mil/ops/defs/reduction.py, coremltools/converters/mil/mil/ops/defs/scatter_gather.py, coremltools/converters/mil/mil/ops/defs/tensor_operation.py, coremltools/converters/mil/mil/ops/defs/tensor_transformation.py, coremltools/converters/onnx/_converter.py, docs/Models/coremltools.models.nearest_neighbors.rst, docs/Models/coremltools.models.neural_network.rst, docs/Models/coremltools.models.tree_ensemble.rst, docs/Models/coremltools.models.utils.rst, docs/index.rst
Fixes Sphinx errors and warnings across the API.
Mostly `WARNING: Inline emphasis start-string without end-string` errors.
Some indentation and blank-line errors.
"References" rubric error.
Title "overline" errors.
Also added onnx.convert to the API. The fix-up commit makes editorial changes.
See [preview](https://coremltools.readme.io/v1.0/reference).
=> Docs: Clean up formatting errors in converter.mil.ops

coremltools/converters/mil/input_types.py, coremltools/models/feature_vectorizer.py, coremltools/models/nearest_neighbors/builder.py, coremltools/models/neural_network/builder.py, coremltools/models/neural_network/update_optimizer_utils.py, coremltools/models/tree_ensemble.py, docs/MIL/coremltools.converters.mil.input_types.rst, docs/Models/coremltools.models.feature_vectorizer.rst, docs/Models/coremltools.models.neural_network.rst, docs/Models/coremltools.models.pipeline.rst, docs/index.rst
This adds and updates the `.rst` files that were manually coded for the
MIL section to include the input_types. The input_types are now part of the MIL section.
The Model `.rst` files (also manually coded) were edited to include member elements:
Added more content to models.neural_network section and added models.feature_vectorizer to the models section.
In addition:
Added `Batch` and `RangeParam` to models.neural_network section by writing docstrings.
Extensive formatting uncovered many properties that needed to be documented in
the models.nearest_neighbors section.
Extensive formatting for models.tree_ensemble section.
See [preview](https://coremltools.readme.io/v1.0/reference/convertersmilinput_types).
=> Docs: Add input_types and other P1 elements to reference section

scripts/conda/build.sh, scripts/conda/meta.yaml
This adds a conda build recipe that builds a development package from a source checkout.  The version number of the package is auto-discovered from the most recent tag, and the package build number is computed using `git describe` to count the number of commits since the most recent tag.  The git hash is also put into the build string for easier debugging.  An example invocation of conda-build looks like:
```
conda build --python=3.8 --numpy=1.16 -c conda-forge scripts/conda
```
The recipe is based on the https://github.com/conda-forge/coremltools-feedstock recipe, but with some changes.
=> Conda build recipe for dev packages built from local source checkout

.gitignore, CMakeLists.txt, scripts/build.sh, scripts/build_tag.py
This adds a `--dist-dev` option to `scripts/build.sh`, which creates wheels in the normal fashion, but adds a "build tag" (sometimes also called a "build number", although it can be more than a number, see https://www.python.org/dev/peps/pep-0427/#file-name-convention).  By default, the build tag will be generated from `git describe --tags` to include the integer count of commits between the current commit and the last tag, as well as the short git hash.
For example, a wheel built with `--dist` will have the filename:
`coremltools-4.0-cp38-none-macosx_10_12_intel.whl`
which is what is uploaded to PyPI.  A wheel built instead with `--dist-dev` will have a filename like:
`coremltools-4.0-22_g1b72c29-cp38-none-macosx_10_12_intel.whl`
which indicates 22 commits between commit `1b72c29` and …
=> Add option to create "developer wheels"

coremltools/converters/onnx/_operators_nd.py, coremltools/converters/onnx/_tests/test_convert.py
If scale factors are not known it is possible to use input and output shapes to calculate them.
=> fix: resize layer conversion with unknown scales

BUILDING.md, CONTRIBUTING.md, README.md
Removing deprecated info in `README.md`, `BUILDING.md`, and `CONTRIBUTING.md`.
=> docs: remove deprecated info in README, BUILDING, and CONTRIBUTING

docs-api/conf.py, docs-api/documentation.md
This PR fixes the API Reference to remove "private" classes that start with underscore (as in `_convert_neural_network_weights_to_fp16` in `coremltools.models.utils`.
To preview this fix, see in [Preview](https://tonybove-apple.github.io/coremltools/index.html):
Click **Models**, and then **utils**. The first non-private class should appear:
`coremltools.models.utils.convert_double_to_float_multiarray_type`
The private class `_convert_neural_network_weights_to_fp16` should _not_ appear.
This PR also includes edits to documentation.md to change "docs-api" to "docs" to prepare for renaming the "docs-api" folder, and to include Sphinx-related install instructions.
=> Sphinx config fix excludes privates plus documentation.md edits

docs-api-version3/index.html
Change the documentation link in version 3.4 introduction from "Version 4.0" to "newest version". This was done directly in the HTML file because we are not re-generating the HTML files for the older version 3.4.
=> Change version link from specific to generic

coremltools/converters/mil/converter.py, coremltools/models/utils.py
Building the documentation, without first building the code, requires that coremltools be both installable and importable in editable mode (i.e. setuptools "develop mode"). So `import` statements can't assume shared library files are built.
=> Fix imports when in "editable mode"

docs/documentation.md
Changes to the `documentation.md` file:
-- Replaced "tonybove-apple" with "sample-user" in the preview URL instruction.
-- Replaced "master" with "main" in GitHub instructions and URLs into GitHub.
=> Documentation.md changes including GitHub master = main

coremltools/converters/_converters_entry.py, docs/conf.py
This PR makes editing changes to the docstring within `_converters_entry.py` to make it more readable and fix formatting problems. 
See [Preview of the changed page](https://tonybove-apple.github.io/coremltools/source/coremltools.converters.mil.html).
=> Edits to ct.convert docstring

.gitlab-ci.yml, CMakeLists.txt, docker/Dockerfile-coremltools-linux, modelpackage/src/ModelPackage.cpp
Fixes compatibility with Ubuntu 18.04 by:
* Downgrading our build image from 20.04 to 18.04
* Fall back to using `<experimental/filesystem>` for compatibility with the libstdc++ on 18.04, with corresponding linking to `stdc++fs`
=> fix: compatibility with Ubuntu 18.04

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
This adds support for `torch.maximum` and `torch.minimum` for the MIL converter with the `torch` frontend.
This closes: https://github.com/apple/coremltools/issues/1045
=> Adding support for torch.minimum and torch.maximum

BUILDING.md, CONTRIBUTING.md, README.md, docs/index.rst
This PR fixes links in documentation files to point to the new version of the [Core ML Model Format Specification](https://apple.github.io/coremltools/mlmodel/index.html). This includes:
```
README.md
BUILDING.md
CONTRIBUTING.md
docs/index.rst
```
See [preview](https://tonybove-apple.github.io/coremltools/index.html) on my fork.
=> Fix links to the Core ML Model Format Specification

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
This fixes a bug when converting various types of batch_norm like from [StdConv2d](https://github.com/rwightman/pytorch-image-models/blob/766b4d32627fc4d1d9d188de81736504215127a0/timm/models/layers/std_conv.py#L26). Those batch norms doesn't have have `running_mean` or `running_var` and uses `training=True` so we can simply move two lines and can resolve the error.
=> Fix bug: support various type of batch_norm

.gitlab-ci.yml, coremltools/converters/mil/backend/mil/passes/test_passes.py, coremltools/converters/mil/test_flexible_shape_inputs.py, coremltools/coremltools/converters/mil/test_flexible_shape_inputs.py, coremltools/models/neural_network/flexible_shape_utils.py
Add tests for 4 combinations, of using flexible shapes with unified converter API: 
(https://coremltools.readme.io/docs/flexible-inputs)
- multiarray input + rangeDim
- multiarray input + enumerated shapes 
- image input + rangeDim
- image input + enumerated shapes
All the 4 tests pass on mac OS Monterey. 
The "image input + rangeDim" combination had a bug in Core ML Framework in mac OS Big Sur, which has been fixed in mac OS Monterey. 
In addition to the unit tests, there is a change in the flexible shape utils file, to make sure that the same shape does not get added twice to the enumerated set. This however has no effect on the correctness of the models with enumerated shapes, even if they repeat the model performs correctly. 
Related issues: #992 , #1249
=> Add unit tests for flexible input shapes

coremltools/converters/mil/backend/nn/op_mapping.py, coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Silu is already supported for the mlprogram backend. 
This should fix #1099
=> Add silu op for neuralnetwork backend

coremltools/converters/_converters_entry.py, coremltools/models/model.py, coremltools/models/tree_ensemble.py
This PR includes the following documentation changes:
* `coremltools/converters/_converters_entry.py`: Minor editing around 5.0b3 changes.
* `coremltools/models/model.py`: Minor editing around 5.0b3 changes.
* `coremltools/models/tree_ensemble.py`: Clarification for example 
(Radar: fix: rdar://81798525 (Coremltools documentation | Example in tutorial))
Note: 2 fix-up commits added to fix some formatting errors.
Preview: https://tonybove-apple.github.io/coremltools/index.html
=> edit docs for v5.0b3 and regenerate API Reference

reqs/build.pip, scripts/env_create.sh
=> arm64 build: use same version of numpy as tensorflow-metal

coremltools/converters/_converters_entry.py, coremltools/converters/mil/mil/ops/defs/tensor_operation.py, coremltools/models/neural_network/builder.py, docs/source/coremltools.converters.mil.mil.ops.defs.rst, docs/source/coremltools.converters.mil.rst
This PR includes the following documentation changes based on warnings from Sphinx while generating the API.
The formatting errors in these files are fixed:
```
modified:   coremltools/converters/_converters_entry.py
modified:   coremltools/converters/mil/mil/ops/defs/tensor_operation.py
modified:   coremltools/models/neural_network/builder.py
```
The `autodoc: failed to import class 'isfinite'` error is fixed by editing this file:
```
```
The `WARNING: duplicate object description of coremltools.converters.mil.mil.Builder.program, other instance in source/coremltools.converters.mil` error is fixed by editing this file:
```
modified:   docs/source/coremltools.converters.mil.rst
```
This PR does _not_ include the generated …
=> Fix Sphinx warnings when generating HTML

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
In some specific cases there's a possibility that unbind operation accepts only one split_size.
Here is the minimum artificial example that breaks current version and causes exception:
```
import torch
import numpy as np
class UnbindModule(torch.nn.Module):
axes = torch.tensor([0])
dims = torch.Size(axes)
for dim in sorted(dims):
x = torch.unsqueeze(x, dim)
return x
model = UnbindModule()
with torch.no_grad():
tr_mod = torch.jit.trace(model, torch.tensor(1.))
batch_network_input = [
ct.TensorType(
name='input',
shape=ct.Shape(
shape=(0,), default=(0,)
),
dtype=np.float32,
),
]
coreml_model = ct.convert(
tr_mod,
inputs=batch_network_input,
minimum_deployment_target=ct.target.iOS14,
compute_units=ct.ComputeUnit.CPU_ONLY
)
```
This PR fixes this …
=> Fixed unbind for one split size

coremltools/converters/mil/backend/nn/op_mapping.py, coremltools/converters/mil/frontend/tensorflow/test/test_ops.py, coremltools/converters/mil/mil/ops/tests/test_conv.py
- `neuralnetwork` backend does not support non zero bias for a convolution with dynamic weights. Hence if a bias is present, it needs to added separately via an add op later
- update tests in test_conv.py: unskip tests for dynamic weights with bias, reduce the number of combinations being tested which were excessive.  
- CI: https://gitlab.com/zach_nation/coremltools/-/pipelines/501885129
=> Update lowering logic of dynamic convolution op to neuralnetwork backend

coremltools/converters/mil/mil/ops/defs/linear.py, coremltools/converters/xgboost/_tree.py, docs/source/coremltools.converters.mil.mil.ops.defs.rst
This PR addresses the following doc problems:
* [rdar://88775719](rdar://88775719) (CoreML Tools Docs Bug)
* [rdar://90672903](rdar://90672903) (Coremltools documentation page lacks einsum op definition)
It includes the following files:
```
modified:   coremltools/converters/mil/mil/ops/defs/linear.py
modified:   coremltools/converters/xgboost/_tree.py
```
=> Add einsum to linear and fix xgboost convert code

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/torchir_passes.py
Fixes two issues found by #1447:
* Output of `empty` op can be input to a `fill_` op (inplace fill).
* No support `empty` op
=> Adds torch op: empty

coremltools/converters/mil/mil/ops/defs/activation.py, coremltools/converters/mil/mil/ops/defs/control_flow.py, coremltools/converters/mil/mil/ops/defs/conv.py, coremltools/converters/mil/mil/ops/defs/elementwise_binary.py, coremltools/converters/mil/mil/ops/defs/elementwise_unary.py, coremltools/converters/mil/mil/ops/defs/image_resizing.py, coremltools/converters/mil/mil/ops/defs/linear.py, coremltools/converters/mil/mil/ops/defs/normalization.py, coremltools/converters/mil/mil/ops/defs/pool.py, coremltools/converters/mil/mil/ops/defs/random.py, coremltools/converters/mil/mil/ops/defs/reduction.py, coremltools/converters/mil/mil/ops/defs/scatter_gather.py, coremltools/converters/mil/mil/ops/defs/tensor_operation.py, coremltools/converters/mil/mil/ops/defs/tensor_transformation.py
This PR edits the attributes in MIL Ops documentation.
It includes the following files:
```
modified:   coremltools/converters/mil/mil/ops/defs/activation.py
modified:   coremltools/converters/mil/mil/ops/defs/control_flow.py
modified:   coremltools/converters/mil/mil/ops/defs/conv.py
modified:   coremltools/converters/mil/mil/ops/defs/elementwise_binary.py
modified:   coremltools/converters/mil/mil/ops/defs/elementwise_unary.py
modified:   coremltools/converters/mil/mil/ops/defs/image_resizing.py
modified:   coremltools/converters/mil/mil/ops/defs/linear.py
modified:   coremltools/converters/mil/mil/ops/defs/normalization.py
modified:   coremltools/converters/mil/mil/ops/defs/pool.py
modified:   coremltools/converters/mil/mil/ops/defs/random.py
modified: …
```
=> Edit Attributes in MIL Ops Docs

coremltools/converters/mil/mil/ops/defs/activation.py, coremltools/converters/mil/mil/ops/defs/control_flow.py, coremltools/converters/mil/mil/ops/defs/image_resizing.py, docs/source/coremltools.converters.mil.mil.ops.defs.rst
This PR adds the missing ops in the MIL Ops documentation, as follows:
- `activation.py` missing `silu` which needed editing.
- `control_flow.py` missing description of `Const`. Misspelled as `const`.
- `control_flow.py` missing Attributes for `make_list`.
- `image_resizing.py` missing:
- `affine` which needed editing.
- `resample` which needed editing.
- `resize_nearest_neighbor` which needed editing.
- `reduction.py` removed `reduce_arg` which has no docstring and is not in "Reduction op implementations" section.
=> Include missing MIL ops and attributes

scripts/env_create.sh
There appears to be a redundant (duplicate) step to install doc requirements in `/scripts/env_create.sh`.
The content of lines `107-111` appears again, verbatim and consecutively, in lines `113-117`:
```bash
if [[ $include_docs_deps == 1 ]]; then
echo "Installing additional document requirements."
python -m pip install -r $COREMLTOOLS_HOME/reqs/docs.pip --upgrade
fi
if [[ $include_docs_deps == 1 ]]; then
echo "Installing additional document requirements."
python -m pip install -r $COREMLTOOLS_HOME/reqs/docs.pip --upgrade
fi
```
This PR simply removes lines `113-118` (line 118 then being the blank line following the removed block).
I'm assuming this duplication is spurious. It appears to be harmless, assuming pip is functioning as expected.
If, for some reason, installing those …
=> Remove duplicate docs.pip install in /scripts/env_create.sh

coremltools/converters/mil/mil/ops/defs/elementwise_binary.py
I think these sentence does not make sense since `logical_XXX` receive only `bool` Tensor. 
At first, I misunderstood that `logical_XXX` accepts `int` and `float` tensor.
Type alias `T` may also be unnecessary.
We can replace `T` with `bool` in this document.
=> Fix doc about element wise logical ops.

coremltools/converters/mil/mil/ops/defs/activation.py, coremltools/converters/mil/mil/ops/defs/conv.py, docs/index.rst
This PR fixes the API Reference documentation as follows:
- `activation.py`: [`Relu6`](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#coremltools.converters.mil.mil.ops.defs.activation.relu6) typo.
- `conv.py`: Fix Returns section and formatting problems in the docstring of [`conv_transpose` op](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#coremltools.converters.mil.mil.ops.defs.conv.conv_transpose).
- `index.rst`: Typo in the first sentence of [the landing page](https://apple.github.io/coremltools/index.html).
=> Typos in relu6 and conv-transpose

coremltools/converters/mil/mil/ops/defs/normalization.py
This PR changes the API Reference documentation as follows:
- `normalization.py`: [`layer_norm`](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#coremltools.converters.mil.mil.ops.defs.normalization.layer_norm) correction to `gamma` and `beta` parameters (rdar://94354229).
Note: Changes to docstrings in 6.0b1, including new compression utilities under [**Models**](https://apple.github.io/coremltools/source/coremltools.models.html), and new output specification for [`convert()`](https://apple.github.io/coremltools/source/coremltools.converters.convert.html), were done and approved in the internal repo before this PR. However, this is the first time they appear in this public repo. …
=> API Reference for v6.0b1 and Layernorm Fix

coremltools/models/model.py
https://github.com/apple/coremltools/issues/1512
=> Fix a bug when destructing coreml model

coremltools/converters/_converters_entry.py, coremltools/converters/mil/input_types.py, docs/source/coremltools.models.ml_program.rst, docs/source/coremltools.models.rst
This PR changes the API Reference documentation as follows:
- `_converters_entry.py`: [`convert`](https://apple.github.io/coremltools/source/coremltools.converters.convert.html#module-coremltools.converters._converters_entry): Correcting formatting and grammar issues.
- `input_types.py`: [`ImageType`](https://apple.github.io/coremltools/source/coremltools.converters.mil.input_types.html#imagetype): Correcting formatting and grammar issues.
- `coremltools.models.rst`: [`Models`](https://apple.github.io/coremltools/source/coremltools.models.html): Making `compression_utils` a submenu.
- Added `coremltools.models.ml_program.rst`: New submenu navigation to show `compression_utils` submenu of separate functions.
This PR does _not_ include the generated HTML. See the following preview: …
=> Formatting fixes and compression submenu

coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
`test_adaptive_avg_pool2d` is missing.
=> Add torch AdaptiveAvgPool2d test.

coremltools/converters/_converters_entry.py, coremltools/converters/libsvm/_libsvm_converter.py, coremltools/converters/mil/mil/ops/defs/iOS15/classify.py, coremltools/converters/mil/mil/ops/defs/iOS15/image_resizing.py, coremltools/converters/mil/mil/ops/defs/iOS15/linear.py, coremltools/converters/mil/mil/ops/defs/iOS15/tensor_operation.py, coremltools/converters/mil/mil/ops/defs/iOS15/tensor_transformation.py, coremltools/converters/mil/mil/ops/defs/iOS16/constexpr_ops.py, coremltools/converters/mil/mil/ops/defs/iOS16/image_resizing.py, coremltools/converters/mil/mil/ops/defs/iOS16/tensor_operation.py, coremltools/converters/mil/mil/ops/defs/iOS16/tensor_transformation.py, coremltools/models/ml_program/compression_utils.py, docs/source/coremltools.converters.mil.mil.ops.defs.rst, docs/source/coremltools.converters.mil.rst
This PR updates the API Reference documentation for version 6.0b2, including a fix to support the separation of MIL ops into `iOS15` and `iOS16` folders and to include the following MIL ops:
* `constexpr_ops` in `iOS16`
* `pixel_unshuffle` in `iOS16/tensor_transformation.py`
* `resample` in `iOS16/image_resizing.py`
* `topk` in `iOS16/tensor_operation.py`
* `classify` in `iOS15`
```
```
This PR also fixes the MIL Builder documentation, which needed only to show `program` with the class:
```
modified:   docs/source/coremltools.converters.mil.rst
```
This PR also includes edits for grammar or formatting:
```
modified:   coremltools/converters/_converters_entry.py
modified: …
```
=> API Ref Update and Fix for MIL Ops

coremltools/__init__.py, coremltools/models/__init__.py
With this change, test_api_visibilities.py passes when run in isolation.
=> Explicitly import things which are getting import implicitly.

coremltools/models/utils.py, coremltools/test/sklearn_tests/test_NuSVC.py, coremltools/test/sklearn_tests/test_NuSVR.py, coremltools/test/sklearn_tests/test_SVC.py, coremltools/test/sklearn_tests/test_SVR.py, coremltools/test/sklearn_tests/test_composite_pipelines.py, coremltools/test/sklearn_tests/test_dict_vectorizer.py, coremltools/test/sklearn_tests/test_glm_classifier.py, coremltools/test/sklearn_tests/test_linear_regression.py, coremltools/test/sklearn_tests/test_random_forest_classifier_numeric.py, coremltools/test/sklearn_tests/test_random_forest_regression_numeric.py, coremltools/test/xgboost_tests/test_boosted_trees_classifier_numeric.py, coremltools/test/xgboost_tests/test_boosted_trees_regression_numeric.py, coremltools/test/xgboost_tests/test_decision_tree_classifier_numeric.py, coremltools/test/xgboost_tests/test_decision_tree_regression_numeric.py
Don't assume source predictions are always stored (in the data frame)  in a column called `prediction`. Instead, assume that column name matches the key in the dictionary returned by `predict`, similar to how we assume input keys to `predict` match other columns. This parameter value defaults to `target`.
This is an API breaking change.
Fixes #58
=> Update API: utils.evaluate_regressor and utils.evaluate_classifier

coremltools/converters/mil/frontend/tensorflow/test/test_ops.py, coremltools/converters/mil/mil/ops/defs/iOS15/tensor_transformation.py
This PR covers the following issue #1556
=> Fix bug in transpose op - don't allow symbolic value in value_inference

coremltools/converters/mil/backend/mil/load.py, scripts/test.sh
Running `test.sh` without `test-package` parameter does not work. It also does not make much sense, since it would take many hours to run all the test not in parallel.
Fixes: #1533
CI run: https://gitlab.com/coremltools1/coremltools/-/pipelines/620009018
=> Make test-package a required parameter to test.sh

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
As per py torch documentation, the torch.scatter method supports the `src` parameter to be either a tensor or a scalar value. However, coremltools does not support a scalar value for the `updates` parameter. This PR updates the `ops._scatter` method to check whether the `updates` parameter is a scalar and fills a tensor with shape `indices.shape` before calling `scatter_along_axis`.
I ran into this issue trying to convert taming-transformers VQGAN model into CoreML. I had to implement the scatter torch op myself, and so I've submitted this PR to publish this fix.
=> fix: Support scalar source parameter in ops.scatter

README.md, coremltools/converters/mil/mil/ops/defs/iOS15/image_resizing.py, coremltools/converters/mil/mil/ops/defs/iOS15/tensor_operation.py, coremltools/converters/mil/mil/ops/defs/iOS16/constexpr_ops.py, coremltools/converters/mil/mil/ops/defs/iOS16/tensor_operation.py, coremltools/converters/mil/mil/ops/defs/iOS16/tensor_transformation.py, coremltools/converters/sklearn/_converter.py, coremltools/converters/xgboost/_tree.py, docs/_static/css/norightmargin.css, docs/conf.py, docs/source/coremltools.converters.mil.mil.ops.defs.rst
This PR updates the API Reference documentation for version 6.0, including a fix to include the following MIL ops:
* `reshape_like` in `iOS16/tensor_transformation.py`
* `fill_like` in `iOS16/tensor_operation.py`
```
```
This PR also edits the ReadMe file:
```
modified:   README.md
```
This PR also includes edits for grammar or formatting:
```
modified:   coremltools/converters/mil/mil/ops/defs/iOS15/image_resizing.py
modified:   coremltools/converters/mil/mil/ops/defs/iOS15/tensor_operation.py
modified:   coremltools/converters/mil/mil/ops/defs/iOS16/constexpr_ops.py
modified:   coremltools/converters/mil/mil/ops/defs/iOS16/tensor_operation.py
modified:   coremltools/converters/mil/mil/ops/defs/iOS16/tensor_transformation …
```
=> API Ref Update for Version 6.0

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Adds support for `baddbmm` op. This missing op triggers issues in https://github.com/apple/coremltools/issues/1555 and https://github.com/apple/coremltools/issues/1601.
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/648315333
=> [PyTorch] Adds support for baddbmm operator.

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
This fixes the GroupNormalization operation to support 2D and 3D inputs as well
=> fix: GroupNormalization torch op definition corrected (issue #1607)

coremltools/converters/sklearn/_logistic_regression.py
Python 3.10 has removed Iterable from collections, we can use collections.abc to import Iterable
=> Fixed _logistic_regression python 3.10 compatibility

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Adds three operators to PyTorch model conversion:
- glu
- hstack
- remainder
Test cases also added for those ops.
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/651060438
=> [PyTorch] Adds torch ops (glu + hstack + remainder)

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Discovered when converting fine tuned T5 Seq2Seq model that min/max ops didn't behave as expected when given two tensors even though it's a supported signature in torch. Modified functionality for both min max to do elementwise min/max when two tensors are provided and to infer keep_dim because torch also accepts inputs of length 2 that are the tensor and axes, and will default keep_dim to False.
torch min documentation: https://pytorch.org/docs/stable/generated/torch.min.html
torch max documentation: https://pytorch.org/docs/stable/generated/torch.max.html
Related issue: https://github.com/apple/coremltools/issues/1561
=> Patch min/max ops to reflect torch functionality

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Background:
- MIL reduce_sum op doesn't support bool input.
- For PyTorch, the `torch.sum` supports bool input, so we need to add a cast to make it compatible with MIL reduce_sum op.
- For TensorFlow, the `tf.reduce_sum` doesn't support bool input, so there is nothing we need to do at the current stage.
This could solve the issue https://github.com/apple/coremltools/issues/1570.
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/657214141
The newly added test case of tf when that CI was run has been removed. As the modification is on PyTorch side, it should be safe to merge.
=> Adds type cast in reduce_sum to support bool in PyTorch.

coremltools/converters/mil/frontend/torch/load.py
**Issue:** #1616
**What does this implement/fix ?**
Adds warning if torch model is not in eval mode.
@TobyRoseman 
Please let me know if any changes are needed.
=> Raise warning when model not in eval mode

reqs/build.pip, setup.py
Fix for CVE https://security.snyk.io/package/pip/protobuf/3.20.1
Build is successful.
=> Bump `protobuf` to 3.20.2 

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Adds a cast for int64 input in argmax op conversion, and also adds a test case for it.
This PR fixes https://github.com/apple/coremltools/issues/1423, and I have tested it locally with that CLIP model.
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/687849507
=> [PyTorch] Adds a cast for int64 input in argmax op conversion

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Fixes: #1360
Also make `torch.nonzero` work with `as_tuple=True`.
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/683963832
=> Torch Where op with one parameter

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Resolve #1693.
Test code:
```
import torch
class MyModel(torch.nn.Module):
return torch.logsumexp(x, dim=1)
print(ct.__version__)
print(torch.__version__)
m = MyModel()
m.eval()
a = torch.ones(1,2)
m = torch.jit.trace(m, a)
model = ct.convert(m, inputs=[ct.TensorType(shape=a.shape)])
out = model.predict({'x': a.numpy()})
print(f'm(a): {m(a)}; out: {out}')
```
Output:
```
6.1
1.12.1
Converting PyTorch Frontend ==> MIL Ops:  75%|█████████████████████▊       | 3/4 [00:00<00:00, 1795.51 ops/s]
Running MIL Common passes:   0%|                                                 | 0/39 [00:00<?, ? passes/s]/Users/chinchangyang/Code/coremltools/envs/coremltools-py3.9/lib/python3.9/site-packages/coremltools/converters/mil/mil/passes/name_sanitization_util …
```
=> Support Torch op logsumexp

coremltools/converters/mil/input_types.py, coremltools/models/array_feature_extractor.py, docs/source/coremltools.converters.mil.input_types.rst
This PR updates the Input Types section to include the InputType class and to fix formatting in other class docstrings. It also edits and fixes formatting in the docstring for `array_feature_extractor`.
```
modified:   coremltools/converters/mil/input_types.py
modified:   coremltools/models/array_feature_extractor.py
modified:   docs/source/coremltools.converters.mil.input_types.rst
```
A subsequent PR provides the generated HTML that includes any other 6.1 docstring changes.
=> Docs - v6.1 Docstring Formatting Changes

coremltools/converters/mil/backend/nn/op_mapping.py, coremltools/converters/mil/mil/ops/tests/test_slice.py
- slice_by_index can be mapped to sliceStatic if slice is working on only one dimension
- This change includes squeeze_mask into such consideration as well
- sliceStatic does not support squeezeMask
resolves #1709
=> Update slice_by_index to sliceStatic mapping

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
I ran into the following error
```
RuntimeError: PyTorch convert function for op 'concat' not implemented.
```
while converting a model like this one
```python
import torch
import torch.nn
print(ct.__version__)
print(torch.__version__)
class Outer(torch.nn.Module):
def __init__(self, model):
super(Outer, self).__init__()
self.model = model
x = self.model(x)
return x
class Inner(torch.nn.Module):
return torch.concat([x, x], dim=-1)
torch_model = Outer(Inner())
torch_model.eval()
x = torch.randn([1, 3], dtype=torch.float)
traced_model = torch.jit.trace(torch_model, x)
model = ct.convert(traced_model, inputs=[ct.TensorType(shape=x.shape)])
```
with `torch==1.12.1`, `coremltools==6.1`.
Weirdly, if I just convert the `Inner` …
=> Add torch.concat as an alias of torch.cat

coremltools/converters/mil/mil/ops/defs/iOS15/recurrent.py
This PR fixes a typo in [`iOS15.recurrent.lstm`](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#coremltools.converters.mil.mil.ops.defs.iOS15.recurrent.lstm), `cell_activation` in formula.
This PR addresses [rdar://103092445](https://rdar.apple.com/problem/103092445) ([Infra] Typo in mil python docs).
A subsequent PR will provide the generated HTML.
=> Docs - Fix Typo in recurrent lstm API (rdar://103092445)

coremltools/converters/mil/mil/ops/defs/iOS15/recurrent.py
This PR fixes the equations in [`recurrent`](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#module-coremltools.converters.mil.mil.ops.defs.iOS15.recurrent) including `gru`, `lstm`, and `rnn`.
Please review the changes, which use proper math notation for the formulas and *also* the "Where:" sections. The following annotated figures provide a preview showing the changes for `gru` and `lstm`. 
Figure 1. `recurrent_gru`
---
Figure 2. `recurrent_lstm`
Note that math notation is not used in the "Parameters:" or other sections, which uses code font for entered code.
A subsequent PR provides the generated HTML that includes any other 6.1 docstring changes.
=> Docs - Recurrent API Equation Format

coremltools/converters/mil/mil/ops/defs/iOS16/tensor_operation.py, coremltools/models/ml_program/compression_utils.py
This PR generates a new version of the API Reference in order to publish any edits and changes made for v6.2. It also fixes typos and equations in the following:
- `tensor_operation.py`, in `topk`: Bad link due to format problem.
- `compression_utils.py`, in `affine_quantize_weights`: Equations and math formatting.
A subsequent PR provides the generated HTML that includes any other 6.2 docstring changes.
docs-v6.2-update-api-ref
=> Docs - Update v6.2 API Reference

coremltools/converters/mil/backend/nn/op_mapping.py
This is a pull request to add two missing characters to the codebase: the `f` of f-strings.
It makes the error message more interpretable when trying to upsample with nearest-neighbour interpolation and non-integer scale factor.
=> adding the f of f-string

coremltools/converters/mil/backend/nn/op_mapping.py, coremltools/converters/mil/frontend/tensorflow/ops.py, coremltools/converters/mil/mil/types/type_double.py
**Who can do more can do less:** in `add_upsample_nn`, why raise an exception for nearest-neighbor interpolation when bilinear interpolation is available?
**Half a loaf is better than none:** in `NonMaxSuppressionV5`, why raise an exception for "soft" NMS when "hard" NMS is available?
This MR follows the logic that converting to an altered but working version of a model is better than failing to convert.
If in doubt about the change in `type_double.py`, see https://github.com/apple/coremltools/blob/main/coremltools/converters/mil/mil/types/type_int.py#L131
=> Fallback to sensible options for Soft NMS and NN upsampling

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
This change maps `torch.amax` to `mb.reduce_max` and `torch.amin` to `mb.reduce_min` and adds corresponding tests.
=> Support torch.amax and torch.amin

coremltools/converters/mil/debugging_utils.py, coremltools/models/model.py, coremltools/models/utils.py, docs/source/coremltools.models.rst
This PR for the public version `coremltools` (in github):
- Adds `CPU_AND_NE` to [MLModel](https://apple.github.io/coremltools/source/coremltools.models.html#coremltools.models.model.MLModel) in the public API Reference. 
```
modified:   coremltools/models/model.py
```
- Adds `converters.mil.debugging_utils.extract_submodel` to the ``.rst`` navigation file and edits the docstring. See screenshot below for placement in the docs.
```
modified:   coremltools/converters/mil/debugging_utils.py
modified:   coremltools/models/model.py
modified:   docs/source/coremltools.models.rst
```
- Edits docstring in `utils.make_pipeline`.
```
modified:   coremltools/models/utils.py
```
This PR addresses the following tasks in [CoreMLTools Documentation Needs](https://quip-apple.com/bbuNAc6FgiMY):
- Add …
=> Docs - Updates Make Pipeline Extract Submodel for 6.3

mlmodel/docs/Format/TreeEnsemble.rst
Quick commit to fix a small typo in the `TreeEnsemble.rst` document.
=> Fix typo in `TreeEnsemble.rst`

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py, coremltools/converters/mil/mil/input_type.py, coremltools/converters/mil/mil/ops/defs/complex_dialect_ops.py, coremltools/converters/mil/mil/passes/defs/lower_complex_dialect_ops.py, coremltools/converters/mil/mil/passes/tests/test_lower_complex_dialect_ops.py, reqs/test.pip
- Adds support for torch.stft and its various options for both complex and real inputs
- Adds support for torchaudio.functional.Spectrogram (and MelSpectrogram) via STFT support and complex support for pad/reshape/abs.
=> Add support for torch STFT & spectrogram

milstoragepython/MilStorage.cpp, milstoragepython/MilStorage.hpp, milstoragepython/MilStoragePython.cpp
This avoids memory copies across the Python-C++ boundary when using `blob_writer`[^1]. That seems to speed up conversion noticeably e.g. converting gpt2-xl (1.5B) goes from ~3 minutes to ~1 minute on my M1 Max MBP
Caveat: my C++ and Pybind are rusty/non-existent so possible I’m totally missing something.
For testing, I’m not sure the best approach but the models I’ve converted seem functional. Is there a way to compare the weight.bin files? I tried comparing them by converting to text (using `od -An -tx1 -v gpt2.mlpackage`) and diffing them. With that approach, they’re not exactly the same: 1,746 lines of the 194,640,384 out are different.
I’m also curious if this reproduces on other machines or is a quirk of something in my setup.
[^1]: My original intent was to address high memory usage …
=> Make `convert` faster

coremltools/converters/mil/mil/passes/graph_pass.md, docs/source/coremltools.models.rst
This PR is for the public version `coremltools` (in github):
- Change [Models](https://apple.github.io/coremltools/source/coremltools.models.html#models) title to **Model APIs**.
- Edit `coremltools/coremltools/converters/mil/mil/passes/graph_pass.md` for grammar and subheadings.
This PR addresses the following tasks in [CoreMLTools Documentation Needs](https://quip-apple.com/bbuNAc6FgiMY):
- Change "Models" to "Model APIs" in GitHub coremltools.
- Edit `graph_pass.md` in GitHub coremltools.
Generated HTML supplied in a separate PR. Click [**Preview**](https://tonybove-apple.github.io/coremltools/).
Branch:
docs-model-apis-graph-pass
=> Docs - Model APIs and Graph Pass

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Add `randn` and `randn_like` for torch frontend.
Fixes #788.
=> Add `randn` and `randn_like` for torch frontend

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py, coremltools/converters/mil/mil/ops/defs/iOS15/tensor_operation.py, coremltools/converters/mil/mil/ops/defs/iOS16/tensor_operation.py, coremltools/converters/mil/mil/ops/tests/test_tensor_operation.py
Fixes #1823, adds translation for the SDPA op thats new in torch 2.0 (https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html) 
Also added value inference method for the "band_part" MIL op, which was missing, and is needed for translating SDPA op
~~CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/859737737~~
~~CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/861086927~~
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/863595934
=> Add translation method for scaled dot product attention torch op

coremltools/converters/mil/mil/ops/defs/_utils.py, coremltools/converters/mil/mil/ops/tests/test_utils.py
Resolve #1763 
If conv uses custom_pad and `pad[r] - effective_ks[r] == -1 and strides[r] == 1`, output_shape equals input_shape.
In this case we should not create new symbol for shape.
I confirmed flexible MultiHeadAttention works with this change.
```python
import torch  # 1.13.1
import numpy as np  # 1.22.3
import coremltools as ct  # 6.2
from ane_transformers.reference.multihead_attention import MultiHeadAttention
N = 10
x = torch.rand(1, 512, 1, N)
y = torch.rand(1, 512, 1, N)
z = torch.rand(1, 512, 1, N)
with torch.no_grad():
layer = MultiHeadAttention(512, n_head=8, dropout=0.0).eval()
jit = torch.jit.trace(layer, (x, y, z))
flexible_shape = ct.Shape(shape=(1, 512, 1, ct.RangeDim(1, 448)))
mlmod_flexible_shape = ct.convert(
jit,
inputs=[
ct.TensorType("q", flexible_shape), …
```
=> not create new symbol with immutable shape convolution.

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
`mul` and `add` currently allow one of the inputs to be `bool`, by promoting to the type of the other input. However, they fail if both inputs are `bool`.
This is not the case with PyTorch, which interprets `*` on two boolean inputs as a logical `and`, and `+` as a logical `or`. This PR adopts the same convention.
The use of bool tensors is frequent to represent masks. For example, `gpt_bigcode` models in the transformers library, such as the StarCoder coding assistants, cannot be converted to Core ML because the following operation is performed on two boolean inputs: https://github.com/huggingface/transformers/blob/33aafc26ee68df65c7d9457259fc3d59f79eef4f/src/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py#L604-L606
The tests show that two `bool` inputs are now supported. Without …
=> Allow `mul` and `add` with bool inputs

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Add translation for `torch.unflatten`
Fix [issue 1868](https://github.com/apple/coremltools/issues/1868)
A unittest for `torch.nn.TransformerEncoderLayer` is also added, since it is claimed to suffer from the absence of `torch.unflatten`. Although I could not reproduce the failure of this layer, it is still good to expand test coverage.
=> add torch.unflatten

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
The [MIL gelu implementation](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#coremltools.converters.mil.mil.ops.defs.iOS15.activation.gelu) accepts tanh or sigmoid approximations, but the frontend asserts that no approximation is requested.
This PR allows the supported approximations to be specified. `tanh` approximation is used in [models such as the ones with the `gpt_bigcode` architecture](https://github.com/huggingface/transformers/blob/33aafc26ee68df65c7d9457259fc3d59f79eef4f/src/transformers/models/gpt_bigcode/configuration_gpt_bigcode.py#L54-L56), so conversion can now proceed by applying the same approximation.
=> Allow gelu approximations

coremltools/converters/mil/frontend/torch/test/test_passes.py, coremltools/converters/mil/frontend/torch/torchir_passes.py
=> Bug fix: inplace op with casting

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
`masked_fill` in PyTorch accepts a fill value specified as an `int` (`0`, for instance), even if the tensor to fill contains floats. The coremltools `select` op requires both inputs to have the same type, and conversion fails in this particular case. This PR tries to ensure that the fill value matches the tensor dtype.
For additional context, causal language models in the `transformers` library recently started using `masked_fill` to prepare the causal attention masks. Since version 4.30.0, many models contain code such as the following:
https://github.com/huggingface/transformers/blob/main/src/transformers/models/clip/modeling_clip.py#L687
Note the use of `0` as fill value, which causes conversion to fail for all these models because it's interpreted as an `int` during conversion. …
=> masked_fill: fill value type must match tensor type

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
This is in particular relevant to convert `torch.baddbmm` as used for StableDiffusion in https://github.com/huggingface/diffusers/blob/v0.8.1/src/diffusers/models/attention.py#L315
=> Add support for int32 beta in torch.baddbmm

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Fixes #1303 for GroupNorm only.
Added a test case for this issue. Without this patch the test fails with
```
cls = <class 'coremltools.converters.mil.mil.builder.Builder'>, val = [6, 1, 1, is28, is29], name = 'reshape_14_shape', before_op = None
@classmethod
def _add_const(cls, val, name, before_op):
if not is_python_value(val):
>           raise ValueError("Cannot add const {}".format(val))
E           ValueError: Cannot add const [6, 1, 1, is28, is29]
coremltools/converters/mil/mil/builder.py:76: ValueError
```
=> Fix GroupNorm dynamic input

coremltools/converters/_converters_entry.py, coremltools/converters/mil/mil/ops/defs/iOS15/elementwise_unary.py, coremltools/converters/mil/mil/ops/defs/iOS17/elementwise_unary.py, coremltools/converters/mil/mil/ops/defs/iOS17/image_resizing.py, coremltools/models/neural_network/builder.py, coremltools/optimize/coreml/_post_training_quantization.py, docs/source/coremltools.converters.mil.mil.ops.defs.rst, docs/source/coremltools.optimize.torch.examples.rst
It updates the following source file docstrings for typos and grammar and formatting errors:
```
modified:   coremltools/converters/_converters_entry.py
modified:   coremltools/converters/mil/mil/ops/defs/iOS17/elementwise_unary.py
modified:   coremltools/converters/mil/mil/ops/defs/iOS17/image_resizing.py
modified:   coremltools/models/neural_network/builder.py
modified:   coremltools/optimize/coreml/_post_training_quantization.py
modified:   docs/source/coremltools.optimize.torch.examples.rst
```
The PR modifies the following to accommodate new ops in the navigation:
```
```
The PR also includes a fix for the following radar: [Doc-Incorrect documentation …
=> Docs - Update API Reference to Version 7.0b2

coremltools/converters/mil/mil/passes/defs/cleanup/const_deduplication.py
Graph pass `const_deduplication` was designed to remove duplicate tensor constants. The edge case "list constant" was not taken into account.
Partially fix [#1937](https://github.com/apple/coremltools/issues/1937)
CI: https://gitlab.com/coremltools1/coremltools/-/commit/5fd0590a4d8b6a106df5385165f6197135c3abbd/pipelines
CI green ✅
=> const_deduplication edge case: ListVar

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Fix [issue #1912](https://github.com/apple/coremltools/issues/1912)
The indices generation from `im2col` is factored out, since it is also applicable here in `col2im`
CI: https://gitlab.com/coremltools1/coremltools/-/commit/14fdf7f8f765ac546f3f7591fee2e72b05e624d5/pipelines
CI green ✅
=> support torch.nn.Fold (col2im)

docs/conf.py, docs/index.rst, docs/source/api-versions.rst
The PR:
- Adds **Previous Versions** to the navigation menu under Resources (`index.rst`), with links to the previously-generated HTML content for previous versions of the API: v3.4, v4.1, and v6.3. Another PR, already merged, adds the folders `v3.4`, `v4.1`, and `v6.3` to the `gh-pages` branch so that these links work.
- Makes edits to the `index.rst` file.
- Adds version number (7.0) to the top left header. This automatically changes when we change `version` in `conf.py`.
Branch:
docs-add-previous-vers-of-api-docs
[**Click for Preview**](https://apple.github.io/coremltools/source/api-versions.html)
=> Docs - Add Previous Versions of API Docs

coremltools/models/utils.py, docs/source/coremltools.models.rst
The PR includes updated API reference docstrings for v7.0. The following was edited to correct an error caught by Sphinx:
```
modified:   coremltools/models/utils.py
```
The following Sphinx error caused `compile_model` to not appear in the documentation:
```
WARNING: error while formatting signature for coremltools.models.utils.compile_model: Handler <function mangle_signature at 0x7fd83060b440> for event 'autodoc-process-signature' threw an exception (exception: Error parsing See Also entry '``coremltools.models.CompiledMLModel``' in the docstring of compile_model in /Users/tonybove/opt/coremltools/coremltools/models/utils.py.)
```
The edits:
- Remove the "See also" reference, as CompiledMLModel did not appear in the …
=> Docs - Update API Reference for v7.0

coremltools/models/_compiled_model.py, coremltools/models/ml_program/compression_utils.py, coremltools/models/model.py
The PR edits the following for formatting changes:
```
modified:   coremltools/models/_compiled_model.py
modified:   coremltools/models/ml_program/compression_utils.py
modified:   coremltools/models/model.py
```
- Fixed Example sections.
- Changed class references to links for deprecated `compression_utils.py`.
- Edited for grammar and minor formatting.
Branch:
docs-fix-format-mlmodel-compiled-mlmodel
---
[**Click for Preview**](https://tonybove-apple.github.io/coremltools/)
=> Docs - Fix Formatting in MLModel and Compiled MLModel

.gitlab-ci.yml
CI test:
https://gitlab.com/coremltools1/coremltools/-/pipelines/996397949
The above the backend test (for both intel and M1) should fail. A fix for these failures will be added in a separate PR.
=> Running missing unit tests in CI

docs-guides/source/performance-impact.md, docs-guides/source/quantization-overview.md
- Re-Run the model with perf tab in Xcode 15 and iOS17 and update latency numbers 
- Add a note about increased int8 NE throughput in A17 pro chips 
For preview see links below. The following changes have been made in this PR: 
- Towards the end of [this section](https://aseemw.github.io/coremltools/docs-guides/source/performance-impact.html#effect-on-latency-and-runtime-memory) updated the links to the overview sections to directly go to the sub section that talks about performance impact
- Update the latency numbers in [this section](https://aseemw.github.io/coremltools/docs-guides/source/performance-impact.html#examples) and also the build version and Xcode version which are used to get the latency numbers. Also add the latency numbers on iPhone 15 pro for 8 bit quantized models. 
- …
=> [Documentation] Update tables in accuracy and performance section 

docs-guides/source/convert-nlp-model.md, docs-guides/source/model-scripting.md, docs-guides/source/model-tracing.md, docs-guides/source/palettization-overview.md, docs-guides/source/post-training-palettization.md, docs-guides/source/updatable-nearest-neighbor-classifier.md
This PR is for the GitHub-hosted public version of `coremltools`; specifically, the `docs-guides` folder. 
This PR edits various files to fix index entry codes so that they work, and also fixes a grammatical error.
```
modified:   source/convert-nlp-model.md
modified:   source/model-scripting.md
modified:   source/model-tracing.md
modified:   source/palettization-overview.md
modified:   source/post-training-palettization.md
modified:   source/updatable-nearest-neighbor-classifier.md
```
Branch:
docs-guides-edit-index-entry-sections
---
**Preview**:
- [Using the book theme](https://tonybove-apple.github.io/coremltools/docs-guides)
=> Docs-Guides - Edit Index Entry Sections

README.md, docs-guides/source/how-to-contribute.md, docs/documentation.md, docs/index.rst
The PR edits the following for links to the "Guide" (or "guides") and grammar/stylistic changes:
```
modified:   ../README.md
modified:   source/how-to-contribute.md
modified:   ../docs/documentation.md
modified:   ../docs/index.rst
```
Branch:
docs-change-links-for-guide
---
**Previews**:
- [coremltools API Reference](https://tonybove-apple.github.io/coremltools/)
- [Core ML Tools Guide](https://tonybove-apple.github.io/coremltools/docs-guides/) Using the book theme
=> Docs - Change Links for the Guide to Sphinx Version

docs-guides/index.rst, docs-guides/source/faqs.md, docs-guides/source/load-and-convert-model.md, docs-guides/source/model-prediction.md, docs-guides/source/new-conversion-options.md, docs-guides/source/overview-coremltools.md, docs-guides/source/typed-execution-example.md, docs-guides/source/typed-execution.md
This PR is for the GitHub-hosted public version of `coremltools`; specifically, the `docs-guides` folder. 
This PR edits various files to fix the following:
- ANE should be "NE" (Apple Neural Engine should be Neural Engine) throughout.
- API reference links:
- Move up in the navigation column to new API section at top.
- Include Core ML Model Format with new API section at top.
- Move Getting Started and Installing into Overview section.
- Move Core ML Tools API Overview into Unified Conversion section.
- Remove Essentials section title.
- Add to Additional Resources section of What Is Core ML Tools.
```
modified:   index.rst
modified:   source/faqs.md
modified:   source/load-and-convert-model.md
modified:   source/model-prediction.md
modified:   source/new-conversion-options.md
modified: …
```
=> Docs-Guides - Neural Engine (NE) and Other Edits

coremltools/converters/mil/mil/passes/defs/optimize_normalization.py, coremltools/converters/mil/mil/passes/tests/test_passes.py
The ml-ane-transformers repo provides a reference implementation of a channels-first layer norm [here](https://github.com/apple/ml-ane-transformers/blob/da64000fa56cc85b0859bc17cb16a3d753b8304a/ane_transformers/reference/layer_norm.py). This adds a pass to replace that with an equivalent MIL `layer_norm` op.
This uses less ops (7 or 9 depending on if the elementwise affine is used) and makes the MIL/graph easier to read. I mostly followed the pattern of the other similar passes, happy to make any adjustments!
=> Add pass for ml-ane-transformers layer_norm

coremltools/converters/mil/mil/ops/defs/iOS15/pool.py, coremltools/converters/mil/mil/ops/defs/iOS15/tensor_transformation.py, docs/conf.py, docs/source/coremltools.converters.mil.mil.ops.defs.rst
This PR edits the following for grammar/stylistic and formatting changes:
```
modified:   coremltools/converters/mil/mil/ops/defs/iOS15/pool.py
modified:   coremltools/converters/mil/mil/ops/defs/iOS15/tensor_transformation.py
```
This PR also adds the `batch_to_space` and `space_to_batch` ops, and changes the version number to 7.1. 
**Note**: All docstring changes merged by others into the 7.1 version of the API will also be generated automatically by `sphinx.ext.autodoc` into HTML for the docs.
```
modified:   docs/conf.py
```
Addresses:
- rdar://116005065
- rdar://116248791
Branch:
docs-avg-pool-space-batch-edits
---
[**Click for Preview**](https://tonybove-apple.github.io/coremltools/)
=> Docs - 7.1 Update and avg_pool and add space_to_batch and batch_to_space

docs-guides/source/faqs.md, docs-guides/source/installing-coremltools.md
This PR updates the installation and other mentions of the version number to 7.1, and fixes a typo.
```
modified:   source/faqs.md
modified:   source/installing-coremltools.md
```
Branch:
docs-guides-update-7.1-typos
---
**Preview**:
- [Core ML Tools Guide](https://tonybove-apple.github.io/coremltools/docs-guides/)
=> Docs-Guides - Update to 7.1 and Fix Typo

coremltools/converters/_converters_entry.py, coremltools/converters/mil/mil/passes/defs/optimize_tensor_operation.py, coremltools/models/utils.py
This PR edits the following for grammar/stylistic and formatting changes:
```
modified:   coremltools/converters/_converters_entry.py
modified:   coremltools/converters/mil/mil/passes/defs/optimize_tensor_operation.py
modified:   coremltools/models/utils.py
```
Branch:
docs-format-docstrings-make-pipeline-etc
=> Docs - Format Docstrings for make_pipeline and Other 7.1 Changes

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
`torch.log` automatically casts arguments to `float32`:
```py
>>> torch.log(torch.tensor([10], dtype=torch.int32))
tensor([2.3026])
```
However, the same operation fails when converting to Core ML.
This patch makes it possible to convert `mistral` models, such as [mistralai/Mistral-7B-Instruct-v0.1](https://hf.co/mistralai/Mistral-7B-Instruct-v0.1).
=> `torch.log()`: cast int arguments to `float32`

coremltools/converters/_converters_entry.py
This PR fixes the following indents and other warnings:
```
docstring of coremltools.converters._converters_entry.convert:165: WARNING: Bullet list ends without a blank line; unexpected unindent.
docstring of coremltools.converters._converters_entry.convert:172: WARNING: Bullet list ends without a blank line; unexpected unindent.
docstring of coremltools.converters._converters_entry.convert:196: ERROR: Unexpected indentation.
docstring of coremltools.converters._converters_entry.convert:224: ERROR: Unexpected indentation.
docstring of coremltools.converters._converters_entry.convert:240: ERROR: Unexpected indentation.
docstring of coremltools.converters._converters_entry.convert:264: ERROR: Unexpected indentation.
docstring of coremltools.converters._converters_entry.convert:333: ERROR: …
```
=> Docs - Sphinx Indents in convert() Docstring

coremltools/converters/mil/frontend/torch/ops.py
In torch 2.1, `scaled_dot_product_attention` now has 7 inputs, whereas 2.0 has only 6. 
2.0 docs: https://pytorch.org/docs/2.0/generated/torch.nn.functional.scaled_dot_product_attention.html#torch.nn.functional.scaled_dot_product_attention
2.1 docs: https://pytorch.org/docs/2.1/generated/torch.nn.functional.scaled_dot_product_attention.html#torch.nn.functional.scaled_dot_product_attention
This PR will allow for both interfaces to work, and simply ignore the new one. This issue arises for any conversion that uses this op on Torch 2.1:
`ValueError: node hidden_states.11 (scaled_dot_product_attention) got 7 input(s), expected [6]`
=> Update scaled_dot_product_attention to work with >6 inputs in latest torch version

coremltools/converters/mil/frontend/torch/ops.py
`t` was already an alias, but sometimes the torch op used is `numpy_T`. This happens, for example, when converting the `falcon` family of models in this line: 
https://github.com/huggingface/transformers/blob/9beb2737d758160e845b66742a0c01201e38007f/src/transformers/models/falcon/modeling_falcon.py#L68
=> Add `numpy_t` as alias of `transpose`

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
To support op with complex data, there are two methods:
1. Decomposing complex data in the op lowering logic, which is suitable for simple logic op such as `add` (it only adds real and imaginary parts separately, and then merge them back into complex data).
2. Use the complex op lowering graph pass, which is suitable for more sophisticated ops such as `fft`, `stft`, etc.
This PR illustrates method 1.
Fixes https://github.com/apple/coremltools/issues/2048.
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1075877628
(those 3 failures are not related to this PR)
=> Supports complex data type for the `add` op.

coremltools/converters/mil/input_types.py, coremltools/converters/mil/mil/ops/defs/iOS15/image_resizing.py, coremltools/converters/mil/mil/ops/defs/iOS16/constexpr_ops.py, coremltools/converters/mil/mil/ops/defs/iOS17/image_resizing.py, coremltools/converters/mil/mil/ops/defs/iOS17/reduction.py, coremltools/converters/mil/mil/ops/defs/iOS17/scatter_gather.py, coremltools/converters/mil/mil/ops/defs/iOS17/tensor_operation.py, coremltools/converters/mil/mil/passes/defs/optimize_repeat_ops.py, coremltools/models/neural_network/builder.py, coremltools/optimize/coreml/_post_training_quantization.py, docs/source/coremltools.models.ml_program.rst, docs/source/coremltools.optimize.coreml.config.rst
[**Click for Preview**](https://tonybove-apple.github.io/coremltools/)
This PR fixes the following indents and other warnings:
```
/Users/tonybove/opt/coremltools/coremltools/converters/mil/input_types.py:docstring of coremltools.converters.mil.input_types.EnumeratedShapes.__init__:9: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/tonybove/opt/coremltools/coremltools/converters/mil/input_types.py:docstring of coremltools.converters.mil.input_types.EnumeratedShapes.__init__:11: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/tonybove/opt/coremltools/coremltools/converters/mil/input_types.py:docstring of coremltools.converters.mil.input_types.EnumeratedShapes.__init__:16: WARNING: Definition list ends without a blank line; …
```
=> Docs - Sphinx Indent Errors in Rest of API Reference

coremltools/models/utils.py, coremltools/test/neural_network/test_compiled_model.py
* For efficiency restrict allowable model types 
* Add instructions for previously allowable types
* Add optional parameter for where to save compiled model
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1075605326
=> Refine compile_model API

mlmodel/docs/Format/Model.rst, mlmodel/docs/index.rst, mlmodel/format/Model.proto
This PR updates [Core ML Model Format Specification](https://apple.github.io/coremltools/mlmodel/index.html) pages; specifically:
Update `Model.proto` and `Model.rst` to include `mlprogram`,  and also edit the introductory paragraph.
---
**Preview**:
- [Core ML Model Format Specification](https://tonybove-apple.github.io/coremltools/mlmodel/)
=> Mlmodel Docs - Update Model.proto and Model.rst

coremltools/converters/mil/frontend/torch/__init__.py, coremltools/converters/mil/frontend/torch/test/test_torch_conversion_api.py, coremltools/converters/mil/frontend/torch/torch_op_registry.py
In ExecuTorch, a partitioner is demanded to determine which part of the exir graph can be executed on which backend. Currently, ExecuTorch provides `CapabilityBasedPartitioner` API, which proposes possible partitions based on whether a PyTorch op (expressed as a `torch.fx.Node`) can run on the specified backend, in our case, Core ML.
From coremltools point of view, this means whether a single `torch.fx.Node` is convertible to pymil
Naturally, we can have such a public API that takes a torch.fx.Node as input, then returns boolean output on whether it is convertible to pymil
```
def is_torch_fx_node_supported(torch_fx_node: torch.fx.Node) -> bool:
```
We have the flexibility to add new kwargs as needed in the future, e.g. something like `device=ANE` if we specifically want to know if a …
=> [PyTorch] Add API to Query if a PyTorch Op is Supported in Core ML

coremltools/converters/mil/mil/builder.py, coremltools/converters/mil/mil/passes/pass_pipeline.py
When the logging level is set to `INFO` (default is `WARNING`), these two statements absolutely flood the logs. In my opinion, both these statements should clearly be debug statements not info statements.
=> Decrease log level for two common log statements

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
* Allow `input`, `mat1` and `mat2` to all be non-const. Previously only `mat1` was allowed to be non-const.
* Support generic matrix shapes. Previously `input` had to be one dimensional.
* Add unit tests. Previously we didn't have any for `torch.addmm`.
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1147306796
=> Make torch.addmm more generic and add unit tests

coremltools/converters/mil/frontend/torch/converter.py, coremltools/converters/mil/frontend/torch/exir_utils.py, coremltools/converters/mil/frontend/torch/internal_graph.py, coremltools/converters/mil/frontend/torch/load.py, coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_executorch_e2e.py, coremltools/converters/mil/frontend/torch/test/test_torch_conversion_api.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py, coremltools/converters/mil/frontend/torch/test/testing_utils.py, coremltools/converters/mil/frontend/torch/torch_op_registry.py, coremltools/converters/mil/frontend/torch/utils.py
In CoreMLTools PyTorch converter, there are 2 naming things that should get sanitized:
1. In ExecuTorch conversion support, we are actually supporting aten dialect of ExIR, rather than edge IR. Also, ExIR is a more general terminology that also applies to `torch.export`. As a result, we should rename all "edge IR" to "ExIR"
2. We have multiple name sanitizing logics for such PyTorch prefix and suffix et ceteral (see our [discussion](https://github.com/apple/coremltools/pull/2081#discussion_r1443207870)). It would be a better practice to unify them into a single utility function
💁‍♂️ Tips for reviewers: review commit-by-commit would be easier
Fix issue [2106](https://github.com/apple/coremltools/issues/2106)
Testing ✅ [GitLab CI](https://gitlab.com/coremltools1/coremltools/-/commit/f2d436fb …
=> [Torch] Sanitize Name Treatment

coremltools/converters/mil/mil/ops/defs/iOS15/elementwise_unary.py, coremltools/converters/mil/mil/ops/tests/iOS15/test_elementwise_unary.py
This pull request addresses a specific issue encountered in the `coremltools` library, particularly within the `cast` operation of `elementwise_unary.py`. The primary aim is to resolve an `AttributeError` that arises when a `float` object is passed to the `cast` function and the `input_var.sym_type` is not a tensor.
The error encountered is as follows:
```
File "/Users/chinchangyang/miniconda3/envs/lczero-training-py3.11/lib/python3.11/site-packages/coremltools/converters/mil/mil/ops/defs/iOS15/elementwise_unary.py", line 894, in get_cast_value
return input_var.val.astype(dtype=string_to_nptype(dtype_val))
^^^^^^^^^^^^^^^^^^^^
AttributeError: 'float' object has no attribute 'astype'
```
This occurs in scenarios where the `cast` operation attempts to call the `.astype()` method on a …
=> Resolve AttributeError in cast for Float Types in Non-Tensor Contexts

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Without this fix we silently produce fp32 random numbers, which is wrong behavior.
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1158229827
=> Error out when asked to produce random complex numbers

docs-guides/source/convert-to-ml-program.md
This PR fixes formatting and punctuation in the Warning section of [Save ML Programs as Model Packages](https://apple.github.io/coremltools/docs-guides/source/convert-to-ml-program.html#save-ml-programs-as-model-packages).
**Preview**:
- [Convert Models to ML Programs](https://tonybove-apple.github.io/coremltools/docs-guides/source/convert-to-ml-program.html)
- [Core ML Tools Guide](https://tonybove-apple.github.io/coremltools/docs-guides/)
=> Docs-Guides - Fix Warning in Save ML Programs as Model Packages

coremltools/converters/mil/frontend/torch/exir_utils.py, coremltools/converters/mil/frontend/torch/internal_graph.py, coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_conversion_api.py, coremltools/converters/mil/frontend/torch/test/testing_utils.py, coremltools/converters/mil/frontend/torch/utils.py
Currently, we export torch model to Apple devices starting from `executorch.exir.capture`
```
exir_program_edge = executorch.exir.capture(torch_model, example_inputs).to_edge(...).exported_program
coreml_model = coremltools.convert(exir_program_edge, ...)
```
However, `executorch.exir.capture` [doc string](https://github.com/pytorch/executorch/blob/release/0.1/exir/capture/_capture.py#L86-L97) declares its deprecation and suggests PyTorch 2.0 standard `torch.export.export` API. So, in this PR, we migrate our export workflow to `torch.export.export`
```
exir_program_aten = torch.export.export(torch_model, example_inputs)
exir_program_edge = executorch.exir.to_edge(exir_program_aten).exported_program()
coreml_model = coremltools.convert(exir_program_edge, ...)
```
Testing: ✅ [GitLab …
=> [ExecuTorch] Migrate Torch Model Export Workflow from "Capture" to "Export"

coremltools/converters/mil/frontend/torch/internal_graph.py, coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/quantization_ops.py, coremltools/converters/mil/frontend/torch/test/test_executorch_quantization.py, coremltools/converters/mil/frontend/torch/test/test_internal_graph.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py, coremltools/converters/mil/frontend/torch/test/testing_utils.py, coremltools/converters/mil/frontend/torch/utils.py
In PyTorch 2 Export, a new exportable [quantization API](https://pytorch.org/docs/stable/quantization.html#prototype-pytorch-2-export-quantization) is introduced
```
model = Model()
example_args = (torch.randn(SHAPE),)
pre_autograd_aten_dialect = capture_pre_autograd_graph(model, example_args)
quantizer = XNNPACKQuantizer().set_global(get_symmetric_quantization_config())
prepared_graph = prepare_pt2e(pre_autograd_aten_dialect, quantizer)
converted_graph = convert_pt2e(prepared_graph)
```
Let us support it in CoreMLTools!
Major changes:
1. Move "torch dtype to number" mapping to lower level [utils.py](https://github.com/apple/coremltools/pull/2138/commits/f83e402df78faf80489694c29313aa16404fecb5#diff-7bb298f719e574ebb257f4ad398bec92fb0dca827ffb9371ba1bfd1b8c7751a0), since now it will not …
=> [PyTorch 2] Support PyTorch 2 Export Quantization

docs-guides/source/comparing-ml-programs-and-neural-networks.md
This PR removes this text from [Differences in Detail](https://apple.github.io/coremltools/docs-guides/source/comparing-ml-programs-and-neural-networks.html#differences-in-detail):
* Integer and LUT weight-only quantization:
ML programs currently support both float 16 and float 32 typed weights and activations.
=> Docs-Guides - Remove Integer and LUT weight-only quantization

coremltools/converters/mil/frontend/torch/test/test_executorch_quantization.py, coremltools/optimize/torch/_utils/python_utils.py, coremltools/optimize/torch/quantization/_annotation_config.py, coremltools/optimize/torch/quantization/_coreml_quantizer.py, coremltools/optimize/torch/quantization/_coreml_quantizer_utils.py, coremltools/test/optimize/torch/quantization/test_coreml_quantizer.py
Adds a `CoreMLQuantizer` which extends [PyTorch 2.0 Export Quantizer](https://pytorch.org/tutorials/prototype/quantization_in_pytorch_2_0_export_tutorial.html) to enable CoreML quantization rules. 
Usage:
```
import torch.nn as nn
from torch._export import capture_pre_autograd_graph
from torch.ao.quantization.quantize_pt2e import convert_pt2e, prepare_qat_pt2e
from coremltools.optimize.torch.quantization._coreml_quantizer import CoreMLQuantizer
model = nn.Sequential(
OrderedDict(
{
"conv": nn.Conv2d(1, 20, (3, 3)),
"relu1": nn.ReLU(),
"conv2": nn.Conv2d(20, 20, (3, 3)),
"relu2": nn.ReLU(),
}
)
)
loss_fn = define_loss()
config = LinearQuantizerConfig.from_dict(
{
"global_config": {
"quantization_scheme": "symmetric",
}
}
)
quantizer = CoreMLQuantizer(config)
example_inputs = torch.randn(1, …
```
=> Add `CoreMLQuantizer` in `coremltools.optimize.torch` to support PyTorch Export based quantization

coremltools/optimize/torch/quantization/quantization_config.py
Fix #2167 
In our [discussion](https://github.com/pytorch/executorch/pull/2338#discussion_r1520577132) with PyTorch developer, starting from ExecuTorch qdtypes are no longer necessary and will be deprecated.
Currently, in coremltools.optimize.torch, our [quantization config](https://github.com/apple/coremltools/blob/main/coremltools/optimize/torch/quantization/quantization_config.py#L187-L211) are using qdtypes since they were required by the torch.fx path. We should update it to also allow usual dtypes.
Testing: ✅
1. [GitLab CI](https://gitlab.com/coremltools1/coremltools/-/commit/3fbbaa3feea36ca97bbe02226e3c26b9833e99ac/pipelines)
2. Locally verified with [ExecuTorch CoreMLQuantizer PR branch](https://github.com/pytorch/executorch/pull/2338)
=> [Optimize] [ExecuTorch] [CoreMLQuantizer] Support `int8` and `uint8` in addition to `qint8` and `quint8`

setup.py
Updates imp to importlib in setup.py file. The load_source function being used was replaced with importlib's spec_from_file_location. This should address issues with future python support.
=> #issue-1846 fixed by updating imp to importlib.

coremltools/models/model.py, coremltools/test/modelpackage/test_modelpackage.py
The root of the saved delegate mapping JSON file is a list, the client has to iterate the list to find the relevant object. The change updated the root object to a dictionary with `version` and `mapping` as the keys.
=> [ExecuTorch] Fix keys in the delegate mapping json file.

coremltools/converters/mil/frontend/_utils.py, coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py, coremltools/converters/mil/frontend/torch/test/testing_utils.py
In our PyTorch converter, we [translate PyTorch indexing to Core ML gather](https://github.com/apple/coremltools/blob/dbb0094fd0cb936469e35320bf37e866ef7a1da4/coremltools/converters/mil/frontend/torch/ops.py#L3684). This works well for float and int, but errors for bool since [Core ML gather does not support bool input](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#coremltools.converters.mil.mil.ops.defs.iOS15.scatter_gather.gather)
In this PR, to support indexing bool tensor, we
1. Cast input bool tensor to a temporary dtype
2. Gather
3. Cast output back to bool
Testing: ✅ [GitLab CI](https://gitlab.com/coremltools1/coremltools/-/commit/207bc95c969de54afeb436772f14a283c9d6fca0/pipelines)
=> Support Indexing Bool Tensor

coremltools/optimize/torch/quantization/_coreml_quantizer_utils.py
PyTorch 2.4 has a [BC-breaking change](https://github.com/pytorch/pytorch/pull/121937/files#diff-20f3c0609d8e134d4450985674a7d720b1f59df511a3b695d16b0aabcc5ba523L23-R23) that wrecks ExecuTorch Core ML quantizer, which is using [PyTorch 2.3 API](https://github.com/pytorch/pytorch/blob/release/2.3/torch/ao/quantization/pt2e/utils.py#L23)
In this PR, we adapt our code to use different APIs given different PyTorch versions
Testing:
1. [GitLab CI](https://gitlab.com/coremltools1/coremltools/-/commit/014fa1b40186e178bb04d41c5a8d4ed5c68ba9c9/pipelines) ~~✅ [GitLab CI](https://gitlab.com/coremltools1/coremltools/-/commit/59c90bba68d4efc7c8dc27da1e5b38cb01e315f0/pipelines)~~
2. ✅ Locally verified with PyTorch 2.4.0.dev20240324
PS: To install nightly PyTorch
```
pip install --pre …
```
=> Make Quantizer Compatible with PyTorch 2.4

coremltools/converters/mil/frontend/torch/test/test_executorch_e2e.py, coremltools/converters/mil/mil/program.py
`ExecuTorch` uses the `Operator` as the key name, the `ExecuTorch` sdk is not showing the operator name. The change renames `Operation_Type` -> `Operator`. 
Tested the change locally.
=> [ExecuTorch] Rename the Operation_Type key to Operator

coremltools/converters/mil/frontend/_utils.py, coremltools/converters/mil/frontend/torch/exir_utils.py, coremltools/converters/mil/frontend/torch/internal_graph.py
This PR does 2 things:
1. Address review comments carried over from https://github.com/apple/coremltools/pull/2181
2. Refactor EXIR internal graph construction, since ExecuTorch now have 3 types of consts: parameter, buffer, constant
Testing:
1. ✅ [GitLab CI](https://gitlab.com/coremltools1/coremltools/-/commit/d191ef513fea511e9b1367c6126d51ade10182ea/pipelines)
2. ✅ Locally verified with ExecuTorch tests
=> [ExecuTorch] Handle 3rd Type of Const in EXIR

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py, coremltools/converters/mil/mil/ops/defs/iOS15/scatter_gather.py, coremltools/converters/mil/mil/ops/tests/iOS14/test_scatter_gather.py
Add support for [torch.select_scatter](https://pytorch.org/docs/stable/generated/torch.select_scatter.html) and [torch.slice_scatter](https://pytorch.org/docs/stable/generated/torch.slice_scatter.html), polish existing support for [torch.index_put_](https://github.com/apple/coremltools/blob/dbb0094fd0cb936469e35320bf37e866ef7a1da4/coremltools/converters/mil/frontend/torch/ops.py#L3599-L3600)
Polish existing support for [torch.copy_](https://github.com/apple/coremltools/blob/dbb0094fd0cb936469e35320bf37e866ef7a1da4/coremltools/converters/mil/frontend/torch/ops.py#L5382-L5383) and [torch.view](https://github.com/apple/coremltools/blob/dbb0094fd0cb936469e35320bf37e866ef7a1da4/coremltools/converters/mil/frontend/torch/ops.py#L1632-L1633) along the way
Testing:
1. ✅ [GitLab …
=> [ExecuTorch] Support Several Indexing Ops

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
The previous implementation of clamp_min defaulted to using float values. By switching to use maximum, this issue is resolved:
```python
class Model(nn.Module):
return torch.clamp_min(x, 1)
ipt = torch.LongTensor([0, 1, 2])
traced_model = torch.jit.trace(Model().eval(), (ipt))
mlmodel = ct.convert(
traced_model,
inputs=[ct.TensorType(name="input", shape=ipt.shape, dtype=types.int32)],
)
mlmodel.save("tmp.mlpackage")
```
This change ensures that the `clamp_min` can handle both float and int32 types.
=> Refactor clamp_min operation to mb.maximum

coremltools/converters/mil/backend/mil/helper.py, coremltools/converters/mil/backend/mil/load.py, coremltools/converters/mil/backend/nn/load.py, coremltools/converters/mil/frontend/_utils.py, coremltools/converters/mil/frontend/torch/exir_utils.py, coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py, coremltools/converters/mil/mil/passes/defs/optimize_quantization.py, coremltools/converters/mil/mil/program.py, coremltools/converters/mil/mil/types/type_tensor.py, coremltools/models/model.py, coremltools/optimize/coreml/_quantization_passes.py, coremltools/optimize/coreml/_utils.py, coremltools/test/optimize/coreml/test_post_training_quantization.py, coremltools/version.py, reqs/docs.pip
✅ [CI](https://gitlab.com/coremltools1/coremltools/-/commit/0d02d1e174b997592f84013fb4d7d5480ade8932/pipelines)
=> 7.2 Release

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Previously, `torch.repeat_interleave` translation only supported `dim is None` or `dim == 0` cases. Since OpenELM uses non-zero `dim`, in this PR we add support for those cases.
Fix https://github.com/apple/coremltools/issues/2207
Testing: ✅ https://gitlab.com/coremltools1/coremltools/-/commit/b62e861aa10e4a06f0b1c9f12dbd199befdc9b2f/pipelines
=> [Torch] Enhance `torch.repeat_interleave` Translation: Support all kinds of `dim`

coremltools/_deps/__init__.py, coremltools/converters/mil/frontend/tensorflow/load.py, coremltools/converters/mil/frontend/tensorflow/test/test_ops.py, coremltools/converters/mil/frontend/tensorflow/tf_graph_pass/constant_propagation.py, coremltools/converters/mil/frontend/tensorflow2/load.py, coremltools/converters/mil/frontend/tensorflow2/test/test_v2_ops_tf_keras.py, coremltools/converters/sklearn/_gradient_boosting_regressor.py, coremltools/converters/sklearn/_imputer.py, coremltools/converters/sklearn/_one_hot_encoder.py, coremltools/optimize/torch/_utils/version_utils.py, coremltools/test/optimize/torch/utils.py, coremltools/test/sklearn_tests/test_NuSVC.py, coremltools/test/sklearn_tests/test_categorical_imputer.py, coremltools/test/sklearn_tests/test_composite_pipelines.py, coremltools/test/sklearn_tests/test_imputer.py, coremltools/test/sklearn_tests/test_one_hot_encoder.py, coremltools/test/sklearn_tests/test_random_forest_classifier_numeric.py, coremltools/test/xgboost_tests/test_decision_tree_classifier_numeric.py, coremltools/test/xgboost_tests/test_decision_tree_regression_numeric.py
Distutils has been deprecated in 3.10 and removed in 3.12 (https://docs.python.org/3.10/whatsnew/3.10.html#distutils-deprecated)
For 3.12 compatibility (#2129) I'm proposing to remove distutils.
distutils was only used for its StrictVersion class, this can be replaced by packaging's Version class in every instance, as this library is already a dependency this requires no further packages to be added as dependency.
For the use of the Version class, see: https://packaging.pypa.io/en/latest/version.html
=> Removing distutils for 3.12 compatibility

coremltools/optimize/torch/layerwise_compression/_quant.py, coremltools/test/optimize/torch/layerwise_compression/test_quant.py
Currently, applying symmetric quantization using GPTQ algorithm with `ct.optimize.torch.layerwise_compression.LayerwiseCompressor` will not produce the correct quantization scales. This may lead to poor accuracy for the quantized model. 
This PR fixes the above mentioned issue and adds corresponding unit tests
=> Fix computation of quantization scales for symmetric quantization with GPTQ

docs-guides/source/mlmodel-utilities.md, docs-guides/source/opt-palettization-api.md, docs-guides/source/opt-quantization-api.md, docs-guides/source/opt-workflow.md
Consistent usage of `coremltools.optimize as cto` across docs-guides
=> [Docs] Updates to docs-guides

setup.py
recently, numpy 2.0.0 was introduced which has breaking changes like 
```
ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
```
=> numpy 2.0.0 breaking changes

coremltools/models/utils.py, coremltools/test/api/test_api_visibilities.py, coremltools/test/ml_program/test_utils.py, docs-guides/source/mlmodel-utilities.md
* This is our proposed solution of issue #2264
* Basically, we moved / and did some slight modification of the [code](https://github.com/apple/ml-stable-diffusion/blob/main/python_coreml_stable_diffusion/chunk_mlprogram.py) in ml-stable-diffusion repo, and put the utils of bisecting a mlpackage under scope of `ct.models.utils.bisect_model`
* After this fix is in, I am going to put another PR in ml-stable-diffusion, and make the `chunk_mlprogram.py` directly calling into this new API, so that any further implementation details changes in coremltools will not break the script itself.
Testing:
~~https://gitlab.com/coremltools1/coremltools/-/pipelines/1389709376~~
~~https://gitlab.com/coremltools1/coremltools/-/pipelines/1389735502~~ …
=> Add bisect_model API under ct.models.utils

coremltools/models/__init__.py, coremltools/optimize/__init__.py, coremltools/test/api/test_api_visibilities.py
Before this PR: 
```
>>> import coremltools as ct
>>> ct.models.array_feature_extractor
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: module 'coremltools.models' has no attribute 'array_feature_extractor'
```
```
>>> ct.optimize.torch
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: module 'coremltools.optimize' has no attribute 'torch'
```
After this PR: 
```
>>> import coremltools as ct
>>> ct.models.array_feature_extractor
<module 'coremltools.models.array_feature_extractor' from '/Volumes/Data/Apple/Repositories/Public/coremltools-public/coremltools/models/array_feature_extractor.py'>
```
```
>>> ct.optimize.torch
<module 'coremltools.optimize.torch' from …
```
=> Surfacing array_feature_extractor as a member of coremltools.models

docs-guides/source/stateful-models.md
This PR includes:
- Link to HuggingFace Mistral-7B post https://huggingface.co/blog/mistral-coreml.
- Add doc for toy stateful attention model.
=> [Doc] Updates documentations about stateful kv-cache models.

coremltools/converters/mil/frontend/torch/ops.py
Previous error message:
`AssertionError: indices shape must equal to input shape for index put operation.`
New error message:
`AssertionError: indices shape (1, is3) must equal to input shape (1, is2, 256) for index put operation.`
=> chore: report shape to user upon index_put error

coremltools/optimize/coreml/_post_training_quantization.py, coremltools/optimize/coreml/experimental/_post_training_quantization.py, coremltools/optimize/torch/layerwise_compression/algorithms.py, coremltools/optimize/torch/layerwise_compression/layerwise_compressor.py, coremltools/optimize/torch/palettization/sensitive_k_means.py, coremltools/optimize/torch/quantization/post_training_quantization.py
This PR reviews and makes edits to the remaining 8 new docstrings in the Core ML Tools public API reference guide.
- Normalize spelling of "lookup table" and "blockwise" in non-code text
- Fixed formatting and removed extra spaces after some periods in non-code text.
- Modified docstrings to conform to Apple style and fix typos
- Re-worded the `joint_compression: bool` argument in the `linear_quantize_weights`, `palettize_weights`, and `prune_weight` methods for clarity.
- Re-worded `LayerwiseCompressorConfig` and `linear_quantize_activations` docstrings for clarity
- Expanded acronyms for MIL, GPTQ, SparseGPT
5 docstrings related to post-training quantization:
- [ModulePostTrainingQuantizerConfig](https://apple.github.io/coremltools/source/coremltools.optimize.torch.quantization.html#core …
=> Review of new Core ML Tools public API docstrings, part 2

coremltools/models/utils.py, coremltools/optimize/coreml/_post_training_quantization.py, coremltools/optimize/torch/layerwise_compression/algorithms.py, coremltools/optimize/torch/layerwise_compression/layerwise_compressor.py, coremltools/optimize/torch/palettization/palettization_config.py, coremltools/optimize/torch/palettization/post_training_palettization.py, coremltools/optimize/torch/palettization/sensitive_k_means.py, coremltools/optimize/torch/quantization/post_training_quantization.py
After an initial round of review and changes to the doc strings for new Core ML Tools APIs, there were some lingering typos and formatting issues, so this PR fixes them.
=> Clean up remaining typos and formatting errors

coremltools/optimize/coreml/_post_training_quantization.py, coremltools/optimize/torch/layerwise_compression/algorithms.py, coremltools/optimize/torch/layerwise_compression/layerwise_compressor.py, coremltools/optimize/torch/palettization/palettizer.py, coremltools/optimize/torch/palettization/post_training_palettization.py, coremltools/optimize/torch/palettization/sensitive_k_means.py, coremltools/optimize/torch/quantization/quantization_config.py, docs/source/coremltools.optimize.torch.palettization.rst
This commit normalizes the spellings for "hyperparameters", "post-training", and "lookup table" across new Core ML Tools API docstrings.
It also fixes the format for two note boxes and for one instance of n-bit.
=> Normalize spellings and fix note format

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
In the previous implementation, `x` was required to be at least rank 3. According to the [PyTorch documentation](https://pytorch.org/docs/stable/generated/torch.nn.Softplus.html), the input to `softplus` is not dependent on rank. This PR also adds the implementation of the `threshold` parameter in certain cases.
=> Fix torch softplus rank limit

mlmodel/src/MILBlob/Fp8.cpp, modelpackage/src/utils/JsonMap.hpp
The errors:
```shell
/workspaces/coremltools/mlmodel/src/MILBlob/Fp8.cpp:34:20: error: 'range_error' is not a member of 'std'
34 |         throw std::range_error("FP8 SetFloat requires rounding for the given value.");
|                    ^~~~~~~~~~~
/workspaces/coremltools/modelpackage/src/utils/JsonMap.hpp:20:10: error: 'unique_ptr' in namespace 'std' does not name a template type
20 |     std::unique_ptr<JsonMapImpl> m_jsonMapImpl;
|          ^~~~~~~~~~
```
Dockerfile of dev container:
```dockerfile
FROM debian:12
RUN echo "Acquire::http::Pipeline-Depth \"0\";" > /etc/apt/apt.conf.d/99nopipelining
RUN apt-get update && \
apt-get install -y ca-certificates && \
update-ca-certificates
RUN apt-get install -y zsh cmake g++ uuid-dev
RUN chsh -s /usr/bin/zsh
COPY …
```
=> Fix compilation error for g++ (Debian 12.2.0-14)

docs/source/coremltools.converters.mil.mil.ops.defs.rst, reqs/docs.pip
This PR includes:
- Add missing IOS18 ops into API doc source (the iOS18 compression ops and recurrent ops).
- Update Sphinx version to avoid regression in future doc update. The current documentation is produced by the latest 7.X Sphinx (`Sphinx==7.4.7`) as shown in https://github.com/apple/coremltools/pull/2343. 
Preview: https://junpeiz.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1462899116
=> [Doc] Update API doc and Sphinx version

.gitlab-ci.yml, coremltools/converters/mil/backend/mil/test_load.py, coremltools/converters/mil/frontend/tensorflow/test/test_ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_export_conversion_api.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py, coremltools/converters/mil/mil/builder.py, coremltools/models/model.py, coremltools/test/blob/test_weights.py, coremltools/test/ml_program/test_utils.py, coremltools/test/optimize/coreml/test_post_training_quantization.py
* Update CI runner tags. Change from outdated OS version specific tags to version agnostic tags.
* Any CI job which can run natively on Apple Silicon, should use an Apple Silicon machine, for load balancing.
* Make CI green.
* Use `MLModel.get_compiled_model_path` rather than a system call.
* Other minor improvements.
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1480782609
=> Update macOS on CI machines

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Example:
```Python
import torch
from torch import nn
from torch.nn import functional as F
from typing import Final
from cp import coremltools as ct
from cp.coremltools.converters.mil.mil import types
class Model(nn.Module):
def forward(self, x: torch.LongTensor) -> torch.Tensor:
return F.one_hot(x, num_classes=10)
model = Model().eval()
x = torch.arange(10)
traced_model = torch.jit.trace(model, (x))
var_dim: Final[ct.RangeDim] = ct.RangeDim(1, 1_000)
mlmodel = ct.convert(
traced_model,
inputs=[
ct.TensorType(name="x", shape=ct.Shape([var_dim]), dtype=types.int32),
],
outputs=[
ct.TensorType(name="y")
],
)
mlmodel.save("tmp.mlpackage")
```
=> Add torch one_hot op

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
This PR introduces support for conversion of torch cat operation that has as an input a list of empty tensors (tensors with one of its dimensions being zero).
Without this fix we'd filter all these empty tensors and subsequently fail on determining the dtype of the output (as we'd have nothing in the input). We basically keep at least one of the empty tensors in the input to make sure dtype information is still available.
Fixes the bug in https://github.com/apple/coremltools/issues/2296.
CI pipeline: https://gitlab.com/coremltools1/coremltools/-/pipelines/1479158242
=> support for zero dimension tensors as an input for cat operation

coremltools/converters/mil/mil/operation.py, coremltools/models/utils.py, coremltools/test/api/test_api_visibilities.py, coremltools/test/ml_program/test_utils.py, docs-guides/source/mlmodel-utilities.md
Introducing a utility function `change_output_tensor_types` that can change the model output tensor types (e.g. from fp32 to fp16). This function will, for a given CoreML model, return a new model that has updated output types for a required set of functions (by default only "main" function output is updated).
CI pipeline: https://gitlab.com/coremltools1/coremltools/-/pipelines/1486307878
=> new change_output_tensor_types API under ct.models.utils

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
```Python
import torch
from torch import nn
from coremltools.converters.mil.mil import types
class Model(nn.Module):
def forward(self, x: torch.Tensor) -> torch.Tensor:
return x.cumsum(dim=-1, dtype=torch.int32)
model = Model().eval()
x = torch.tensor([0.5, 1.5, 2.5])
y = model(x)
print(y)
traced_model = torch.jit.trace(model, (x))
mlmodel = ct.convert(
traced_model,
inputs=[
ct.TensorType(name="x", shape=x.shape, dtype=types.fp32),
],
outputs=[
ct.TensorType(name="y"),
],
)
mlmodel.save("tmp.mlpackage")
```
It will get the right result.
=> Add torch cumsum dtype support

BUILDING.md
There was a typo in the `BUILDING.md` about where the environments were located. The typo has been fixed
=> [Docs] correct typo in folder name

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Add dtype support and unit test.
The old PR #2345 is a wrong implementation.
=> Enhance torch.zeros_like for GPU inference in dynamic shape

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Support sort ops translation from torch.export
1. sort
2. argsort
Testing: https://gitlab.com/coremltools1/coremltools/-/commit/16a7f14d1339eae93c168b1fb1eedaa97bc08e61/pipelines
=> [Torch.Export] Support Sort Ops Translation

coremltools/models/compute_device.py, coremltools/models/compute_plan.py, coremltools/models/model.py, docs-guides/conf.py, docs-guides/source/mlmodel-utilities.md, docs/conf.py, docs/source/coremltools.models.rst
CI : https://gitlab.com/coremltools1/coremltools/-/pipelines/1556980020
- Updated `conf` to point to 8.1 docs  
- Minor changes to code documentation 
- Added examples for Compute Plan and In-memory model usage.
- [Compute Plan doc](http://htmlpreview.github.io/?https://github.com/cymbalrush/coremltools/blob/gh-pages/docs/source/coremltools.models.html#module-coremltools.models.compute_plan) 
- [Compute Plan guide](http://htmlpreview.github.io/?https://github.com/cymbalrush/coremltools/blob/gh-pages/docs-guides/source/mlmodel-utilities.html#compute-plan)
=> Update docs and add examples for Compute Plan and In-memory model usage.

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
Although we already have `torch.group_norm` support, [ExecuTorch issue #6817](https://github.com/pytorch/executorch/issues/6817) uses `torch.native_group_norm`, so we need to add it
This PR
1. Factors out the group norm implementation, so both `torch.group_norm` & `torch.native_group_norm` translation functions can share
2. Add `torch.native_group_norm` translation function
Testing:
✅ https://gitlab.com/coremltools1/coremltools/-/commit/83fa94df6d52f848be8b2f8577ff67dab117dca1/pipelines
=> [Torch.Export] Support `torch.native_group_norm` Op

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
fixes #2412
@TobyRoseman where should I add testcases for this? I grep'ed through the tests, there are currently none for `torch.linspace`. And having quick tutorial how to get the test locally running would be great, too :) Getting `RuntimeError: BlobWriter not loaded` when calling `ct.convert`.
=> fix torch.linspace

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
This PR adds support for converting the following model:
```Python
import torch
from torch import nn
from typing import Final
class Model(nn.Module):
def forward(self, x: torch.Tensor) -> torch.Tensor:
a, _, b = x.shape
return torch.zeros([a, b])
model = Model().eval()
traced_model = torch.jit.script(model)
var_dim: Final[ct.RangeDim] = ct.RangeDim(1, 10_000)
mlmodel = ct.convert(
traced_model,
inputs=[ct.TensorType(name="x", shape=ct.Shape([1, 3, var_dim]))],
outputs=[ct.TensorType(name="y")],
)
mlmodel.save("tmp.mlpackage")
```
=> Add torch.jit.script shape support

coremltools/converters/mil/debugging_utils.py, coremltools/converters/mil/mil/tests/test_debug.py
Using the `extract_submodel` debugging_util to add additional outputs fails for deployment target >=iOS 16 when the model is converted from PyTorch.
Running this script:
```python
from coremltools.converters.mil.debugging_utils import extract_submodel
import torch
from torch import nn
import numpy as np
class Net(nn.Module):
x = x * x
chunks = x.chunk(5, dim=-1)
transformed = []
for i in range(len(chunks)):
transformed.append(chunks[i] * i)
x = torch.cat(transformed, dim=-1)
x = x ** 0.5
return x
sample_input = torch.randn(1,32,1,512)
full_model = ct.convert(torch.jit.trace(Net().eval(), sample_input),
inputs=[ct.TensorType(shape=sample_input.shape, dtype=np.float16)],
minimum_deployment_target=ct.target.iOS16,
convert_to="mlprogram") …
```
=> Support multiple outputs in extract_submodel for  >=iOS 16

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
It's due to that torchscript produces 5/6 inputs, while torch.export only produces 1 input for that specific model.
Fixes https://github.com/apple/coremltools/issues/2443.
Testing: https://gitlab.com/coremltools1/coremltools/-/pipelines/1664432907
=> Fix the randn conversion failure encountered in torch.export.

coremltools/converters/mil/frontend/torch/ops.py
In `full` op convert, dtype info might be retrieved in `node.kwinputs` instead of `node.inputs`.
=> [Executorch] Fix missing dtype issue in full op delegate

coremltools/converters/mil/frontend/torch/exir_utils.py
Contains two fixes for symbolic variable processing:
1. Process -infinity like +infinity.
2. Throw error when encouring expressions like "2*s0"
On 2, @YifanShenSZ if CoreML supports having related range dim variables, let me know and we can do something else for 2.
=> Symbolic variable fixes

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
- Modified the _construct_conv_transpose method in converters/mil/frontend/torch/ops.py to add an ending mask in mb.slice_by_index when the end index is zero. This occurs when output_padding equals padding.
- Added the test case test_convolution_transpose1d_output_padding.
- Verified that the test passes when output_padding equals padding and that normal cases are not affected.
- Executed the test_convolution_transpose1d_output_padding test case on macOS 11 with a CPU target. Verified that the Torch output is equal to the mlprogram/neuralnetwork output.
- Code changes adhere to the project's coding standards.
- Tests have been added/updated to verify the fix.
=> [#1946] Fix torch.nn.ConvTranspose1d conversion error when output_padding equals to padding

coremltools/converters/mil/mil/passes/defs/optimize_tensor_operation.py, coremltools/converters/mil/mil/passes/tests/test_passes.py
Before this PR, the added tests would error with an undefined attribute error, when `end_mask` was not specified on the `slice_by_index` operations.
Instead of bailing out of the optimization, if `end_mask` is not specified, this PR will infer the values of `end_mask`.
=> Fix the reflection padding optimization when slice_by_index's `end_mask` is not specified

coremltools/converters/mil/mil/ops/defs/iOS15/elementwise_unary.py
I read in an issue that in some cases `np.array(copy=False)` fails: https://github.com/apple/coremltools/issues/2479#issuecomment-2812736201
It's recommended to migrate to `np.asarray()` (without copy):
https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
=> fix: numpy 2 prefers asarray() instead of copy=False

coremltools/optimize/coreml/_post_training_quantization.py, coremltools/optimize/coreml/experimental/_post_training_quantization.py
Updated path since `coremltools.optimize.coreml` houses PTQ-related functions.
There to be inconsistencies of naming in the codebase; I see some usages of:
```python
import coremltools.optimize.coreml as cto
```
and some of:
```python
import coremltools.optimize as cto
cto.coreml.(...)
```
Not sure if there is a convention to follow here.
=> docs: update cto.coreml path in ptq docs

coremltools/optimize/coreml/_quantization_passes.py
For unary and/or binary ops, we want to ensure that input X is non-const when creating Q/DQ pair. Activation stats are not tracked for const ops
https://github.com/apple/coremltools/blob/30a96886b59c8202a67e6b64451c3b1156c79da5/coremltools/optimize/coreml/experimental/_post_training_quantization.py#L228
and trying to run activation quantization yields the following:
```bash
Running activation compression pass insert_prefix_quantize_dequantize_pair:  15%|█████████▉                                                        | 187/1238 [00:00<00:00, 311738.81 ops/s]
Traceback (most recent call last):
File "/Users/jamxu/Documents/coreml/ios-experiments/w8a8_quantize.py”, line 63, in <module>
compressed_model_a8 = cto.coreml.linear_quantize_activations(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> [Quantization (cto.coreml)] Ensure inputs are non-const before adding Q/DQ pair

coremltools/models/ml_program/experimental/debugging_utils.py, coremltools/test/ml_program/experimental/test_debugging_utils.py
```
x2 = mb.real_div(x=x1, y=y, name="div1")
x3 = mb.real_div(x=x1, y=y, name="div2")
```
The following change ensures that x2 and x3 are treated as distinct operations, even though both are created using mb.real_div(x=x1, y=y, ...). Previously, x3 could be eliminated by common subexpression elimination (CSE) due to its identical inputs. By explicitly distinguishing these operations, we prevent unintended optimization.
Additionally, this update enhances both MLModelValidator and MLModelComparator by adding checks to ensure that the same operation is not added to the result list multiple times.
CI:
https://gitlab.com/coremltools1/coremltools/-/pipelines/1851846848
=> Fix failing MLModelValidator tests

coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
This PR replaces the direct torch operator of `pytest.mark.parametrize` with `getattr` in `test_torch_ops` to support parallel testing via `pytest-xdist`.
---
Executing all unit tests on a single device takes too long. To accelerate this process, I would like to leverage parallel execution with `pytest-xdist`. However, some test cases in `test_torch_ops` are incompatible.
When running:
```sh
pytest -n 4 --disable-warnings -x coremltools/converters/mil/frontend/torch/test/test_torch_ops.py::TestVarStd
pytest -n 4 --disable-warnings -x coremltools/converters/mil/frontend/torch/test/test_torch_ops.py::TestTorchTensor::test_torch_rank0_tensor
pytest -n 4 --disable-warnings -x coremltools/converters/mil/frontend/torch/test/test_torch_ops.py::TestSTFT
```
The following error occurs:
```terminal …
```
=> Fix pytest-xdist compatibility in test_torch_ops

coremltools/converters/mil/mil/passes/defs/optimize_activation_quantization.py, coremltools/optimize/coreml/_quantization_passes.py, coremltools/test/optimize/coreml/test_passes.py
Add support for linear op in activation quantization.
One unit test is added.
=> Add linear as a supported op for activation quantization.

coremltools/converters/mil/frontend/torch/quantization_ops.py, coremltools/converters/mil/frontend/torch/test/test_torch_quantization_ops.py
This adds support for torchao's dequantize affine to coremltools.  With this change, users can now quantize PyTorch models with torchao APIs like this:
```
quantize_(
model,
IntxWeightOnlyConfig(torch.int4, PerGroup(32)),
)
```
This model can then be exported and converted to CoreML:
```
ep = torch.export.export(model, example_inputs)
mlmodel = ct.convert(ep)
```
This corresponds to similar support in ExecuTorch's codebase added here: https://github.com/pytorch/executorch/pull/12664 
I do have some questions about compatibility with coremltools versions of torch/torchao.  This change is tested on torch 2.7 and torchao 0.10, both of which are older than what coremltools uses.
=> Add torchao.dequantize_affine

reqs/pytorch.pip
Torch has released 2.8, but we support up to 2.7.1 for now. Before we upgrade coremltools to be compatible with torch 2.8, let us limit torch < 2.8 in CI for now
CI ✅ https://gitlab.com/coremltools1/coremltools/-/commit/463b494215a5f6f9ef73e913e8d60a25fe8c472d/pipelines
=> [CI] Limit Torch to older than 2.8

coremltools/converters/mil/frontend/torch/ops.py, coremltools/converters/mil/test/test_rms_norm.py
Fixes #2585 
Added PyTorch nn.RMSNorm to CoreML conversion by decomposing into primitive MIL operations.
Decompose RMSNorm formula into `mb` composable functions:
1. square
2. reduce_mean
3. add
4. sqrt
5. real_div
6. mul
- [RMSNorm paper](https://arxiv.org/pdf/1910.07467.pdf)
- [PyTorch implementation](https://github.com/pytorch/pytorch/blob/v2.4.0/torch/nn/modules/normalization.py#L321)
=> Add RMSNorm operator support for PyTorch to CoreML conversion (#2585)

docs-guides/source/mlmodel-debugging-perf-utilities.md
small spelling mistake compute_units instead of compute_unit
=> spelling mistake
