coremlpython/CoreMLPythonUtils.mm
coremltools/test/test_io_types.py

CoreML models support grayscale image outputs, but coremlpython asserts only for kCVPixelFormatType_32BGRA. Thus I added kCVPixelFormatType_OneComponent8 support.

Add support for grayscale image outputs in python predictions

---

coremltools/converters/caffe/_caffe_converter.py
coremltools/converters/keras/_keras_converter.py
coremltools/models/neural_network.py

This also updates the Keras converter documentation to render parameters properly.

Update is_bgr documentation to help clarify its role

---

coremltools/converters/keras/_keras2_converter.py
coremltools/converters/keras/_keras_converter.py

Supports converting Keras models with custom objects such as custom loss, optimizers, etc. to coreML model

Adds support for converting Keras models with custom objects

---

coremltools/converters/keras/_keras2_converter.py
coremltools/converters/keras/_layers2.py
coremltools/models/model.py
coremltools/models/neural_network.py

This PR adds custom activation function support.

Add custom activation support

---

docker/Dockerfile-python2.7-build
docker/Dockerfile-python2.7-test
docker/Dockerfile-python3.5-build
docker/Dockerfile-python3.5-test
docker/Dockerfile-python3.6-build
docker/Dockerfile-python3.6-test

* mpfr current version is now 4.0.1 - updating this dependency and
pinning the version explicitly (so the URL won't break again)
* Add node.js and libx11-devel to allow for building Turi Create from
source with Linux native visualization support

Update Docker images

---

coremltools/converters/keras/_keras2_converter.py
coremltools/models/_infer_shapes_nn_mlmodel.py

Addresses issues #165 and #151 
This PR also fixes a bug while converting a Keras model with separate model and weight files.

Correct Flatten shape

---

coremltools/models/model.py
coremltools/test/test_model.py

@znation @srikris @gustavla I can't add reviewers so tagging you in a comment

fixes #198 -- added unit test as well

---

coremltools/converters/keras/_keras2_converter.py
coremltools/converters/keras/_keras_converter.py
coremltools/test/test_keras2_numeric.py

Modified signature of Keras converter's convert function to include a dictionary from input names to their shapes.

Included input_name_shape_dict argument in Keras converter function

---

README.md
docs/APIExamples.md

Inspired from the issue here: https://github.com/tf-coreml/tf-coreml/issues/242
Also moved the location of the link to Code snippets in the readme file, so that it can be found more easily.

Add code snippet to change datatype for multi-arrays

---

coremltools/converters/keras/_keras2_converter.py
coremltools/converters/keras/_layers2.py
coremltools/test/test_keras2_numeric.py

Should resolve issue #269.
All the Keras tests are passing locally.

Update Keras converter to convert sequence of images

---

coremltools/models/utils.py

Update ignore_layers list in quantize function

---

coremltools/converters/sklearn/_svm_common.py
coremltools/models/neural_network/quantization_utils.py
coremltools/test/test_shaper_bindings.py
coremltools/test/test_tf_numeric.py

Addresses some of the failures from #228

Fix some Python 3.7 unit test failures

---

coremltools/converters/nnssa/commons/basic_graph_ops.py
coremltools/converters/nnssa/frontend/graph_pass/type_inference.py
coremltools/converters/nnssa/frontend/tensorflow/parsed_tf_node.py

OPs included are less , greater, greaterEqual, lessEqual.

Fixing type inference pass for 4 elementwise binary ops

---

coremltools/converters/nnssa/coreml/shapes.py
coremltools/converters/nnssa/coreml/ssa_converter.py
coremltools/converters/nnssa/frontend/graph_pass/type_inference.py

New layers:
- Reduce Max
- Exp
- Square
- RealDiv
Type Inference pass:
- BiasAdd
- SquaredDifference
- Pow
- FloorMod

Hooking up some layers and fixing type inference pass for some broadcastable ops

---

coremltools/converters/nnssa/coreml/shapes.py
coremltools/converters/nnssa/coreml/ssa_converter.py
coremltools/converters/nnssa/frontend/graph_pass/trace_constants.py
coremltools/converters/nnssa/frontend/graph_pass/type_inference.py
coremltools/converters/nnssa/frontend/tensorflow/graph_pass/constant_propagation.py
coremltools/converters/tensorflow/test/test_base.py
coremltools/converters/tensorflow/test/test_convnets.py
coremltools/converters/tensorflow/test/test_tf_graphs.py

- Add new conversion functions
- Single layer tests

Add convert functions and single layer tests

---

mlmodel/docs/index.rst
mlmodel/docs/sections/ItemSimilarityRecommender.rst
mlmodel/docs/sections/LinkedModel.rst
mlmodel/docs/sections/NearestNeighbors.rst
mlmodel/docs/sections/SoundAnalysisPreprocessing.rst
mlmodel/format/Model.proto

Updating coremltools 3.0 beta documentation. Documentation for some new model types was missing

Updating coremltools 3.0 beta documentation

---

coremltools/converters/xgboost/_tree.py
coremltools/converters/xgboost/_tree_ensemble.py
coremltools/test/test_boosted_trees_classifier.py
coremltools/test/test_boosted_trees_classifier_numeric.py

This solves https://github.com/apple/coremltools/issues/174
It will allow users to convert an xgboost classifier model to a coreml one. 
It is the first time I submit a PR in an open-source project so I don't really know the rules (and haven't found any for this project in particular). In particular, I don't know if I respected all the linting conventions of this project.
I didn't write unit tests for this yet, but I am opening the PR anyway just to get some reviews in case I am doing something terribly wrong. I am in the process of writing them.

Xgboost classifier conversion

---

setup.py

Update numpy to first version that support Python 3.7

---

README.md

Correct README to use the official name.

[README] 'CoreML' -> 'Core ML'

---

coremltools/converters/nnssa/coreml/graph_pass/__init__.py
coremltools/converters/nnssa/coreml/graph_pass/op_fusions.py
coremltools/converters/nnssa/coreml/shapes.py
coremltools/converters/nnssa/coreml/ssa_converter.py
coremltools/converters/nnssa/frontend/graph_pass/type_inference.py
coremltools/converters/nnssa/frontend/tensorflow/load.py
coremltools/converters/tensorflow/_tf_converter.py
coremltools/converters/tensorflow/test/test_base.py
coremltools/converters/tensorflow/test/test_tf_graphs.py
coremltools/converters/tensorflow/test/test_utils.py
coremltools/models/utils.py
coremltools/test/test_model.py

This PR:
(1) Adds fusion operation of tf.contrib.layer_norm and GeLU and unit test
(2) Adds random uniform conversion function and unit test
(3) improve static shape inference for TensorArray conversions

Layernorm and GeLU fusion, RandomUniform and Static shape inference

---

coremltools/models/neural_network/builder.py
coremltools/test/test_numpy_nn_layers.py

Setting rank to 1 if rank is 0 for squeeze
Renaming internal functions

Updating rank information for reduce ops using axes

---

examples/updatable_models/OnDeviceTraining_API_Usage.html
examples/updatable_models/README.md

short tutorial on CoreML 3.0 Update Task API usage

On-Device Model Personalization API Usage

---

coremltools/converters/nnssa/coreml/graph_pass/op_fusions.py
coremltools/converters/nnssa/coreml/ssa_converter.py
coremltools/converters/nnssa/frontend/graph_pass/type_inference.py

This PR fixes small bugs in Gather op type inference and TensorArray conversion.

Bug fix in Gather op type inference and TensorArray conversion

---

coremltools/converters/nnssa/commons/builtins/type_tensor.py
coremltools/converters/nnssa/coreml/graph_pass/__init__.py
coremltools/converters/nnssa/coreml/graph_pass/op_fusions.py
coremltools/converters/nnssa/coreml/shapes.py
coremltools/converters/nnssa/coreml/ssa_converter.py
coremltools/converters/nnssa/frontend/graph_pass/type_inference.py
coremltools/converters/tensorflow/test/test_convnets.py

Add op fusions graph passes. BN, Pad into Conv, Reduce to Pooling.
Fix issues in type inference and convert functions.

Add op fusions graph passes. Fix issues in type inference and convert functions.

---

coremltools/converters/nnssa/coreml/shapes.py
coremltools/converters/nnssa/coreml/ssa_converter.py
coremltools/converters/nnssa/frontend/graph_pass/type_inference.py
coremltools/converters/tensorflow/_tf_converter.py
coremltools/converters/tensorflow/test/test_custom_layer.py

- custom layer, custom conversion function, custom shape function
- adding test case with both custom conversion and custom layer

Adding custom layer option

---

coremltools/converters/nnssa/coreml/ssa_converter.py
coremltools/converters/nnssa/nnssa.py
coremltools/converters/tensorflow/_tf_converter.py
coremltools/models/neural_network/builder.py

Adding image_input_names and related, predicted_feature_name and related options
- Image input support in coremltools/tensorflow new path
- Updating script to handle images and models
- Adding test case for 'classifier' and image input
- Handling image pre-processing required to handle NCHW and NHWC format
in builder's `set_pre_processing_parameters`
- Collecting image format through NetworkEnsemble pass

Adding tf converter options into tf coremltools path

---

coremltools/graph_visualization/app.js
coremltools/graph_visualization/index.html
coremltools/models/model.py

I've added the custom title to visualize_spec which is displayed on web page 
This PR closes #505.

Custom title in visualize_spec

---

coremltools/converters/nnssa/coreml/graph_pass/mlmodel_passes.py
coremltools/test/neural_network/test_graph_passes.py

ConvT -> BN -> Activation -> t Crop pattern

Adding MLModel pass to convert ConvT -> Crop -> BN -> Activation to

---

README.md
docs/NeuralNetworkGuide.md

- Update TensorFlow 2.x conversion examples.
- Fix typos.
- Consistent names.

Minor update for docs

---

coremltools/converters/nnssa/coreml/graph_pass/__init__.py
coremltools/converters/nnssa/coreml/graph_pass/mlmodel_passes.py
coremltools/converters/nnssa/coreml/ssa_converter.py
coremltools/converters/tensorflow/test/test_tf_graphs.py
coremltools/test/neural_network/test_graph_passes.py

- If layer's output is not used, remove the layer from MLModel
- Replacing remove_dead_constants pass by new pass
- Update use count to out degree
- Fix out degree computation for loop and branch
Update use count to out degree and comment update

- Adding Dead Layer Removal pass

---

coremltools/converters/nnssa/coreml/shapes.py
coremltools/converters/nnssa/coreml/ssa_converter.py
coremltools/converters/tensorflow/test/test_convnets.py

- Falling back to braodcastable op if scalar is not from Const and not a
tensor

- Fixing typo in convert_binary leading to failure

---

docs/NeuralNetworkGuide.md
examples/neural_network_inference/tensorflow_converter/Tensorflow_2/tf_keras_fashion_mnist.ipynb

Make the documentation more clear. Right now its not very clear and leads to confusions such as issue #516

Code snippet to get input/output names from tf.keras model

---

docs/NeuralNetworkGuide.md

Since `target_ios` has been renamed to `minimum_ios_deployment_target` in the onnx converter as well.

Update onnx section in NN guide

---

coremltools/converters/nnssa/coreml/graph_pass/mlmodel_passes.py
coremltools/test/neural_network/test_graph_passes.py

1. Delete branch layer if if-else branch is empty
2. Delete Loop layer if condition or body network is empty

Updating dead layer elimination mlmodel pass to

---

README.md
coremltools/converters/nnssa/coreml/graph_pass/op_fusions.py
coremltools/converters/tensorflow/_tf_converter.py
coremltools/converters/tensorflow/test/test_tf_2x.py
docs/NeuralNetworkGuide.md

https://github.com/apple/coremltools/issues/553

Fix a conversion bug in TF2 conv with softmax.

---

examples/neural_network_inference/onnx_converter/small_example.py

Update the example with the latest interface of the function "convert"

Update the example with latest interface

---

docs/APIExamples.md

@anilkatti can you please review this PR.

Update image input example code snippet

---

.travis.yml

- Simple setup script to build and test wheels for Linux.
- Does not test macOS.

Added Travis-CI for basic Linux testing

---

README.md

- Shows build status
- Shows python versions
- Shows package version

Added badges to the readme.md file.

---

BUILD.md
README.md

Updated the build instructions so it's easier to test.
@aseemw I mostly removed the dependencies because they are captured in pip so it's not exactly useful. It was also stale.

Updated instructions in Readme.md and Build.md

---

coremltools/graph_visualization/app.js

Graph Visualization: Don't alter string capitalization

---

build_requirements.pip
configure
coremltools/test/neural_network/test_numpy_nn_layers.py
requirements.pip
scripts/make_wheel.sh
test_requirements.pip

Add back support for older versions of numpy

---

coremltools/test/sklearn/test_utils.py

Fixes a flaky test to re-enable it.

Fixes flaky test due to floating point comparisons

---

scripts/test_wheel.sh

- Adds more than just failures. Complete summary
- Adds durations of 100 slowest tests
- Disables warnings in the print out

Cleaned up the pytest output in the CI

---

.gitlab-ci.yml
docker/Dockerfile-python3.7-build

Building the image now, and think I've got all the dependencies needed to run build and test targets on the wheels.

Adding ubuntu based build and test docker image

---

coremltools/__init__.py

Updated version for coremltools.

---

coremltools/converters/nnssa/coreml/graph_pass/mlmodel_passes.py
coremltools/test/neural_network/test_graph_passes.py

Fixing a bug in my redundant transpose removal pass, due to my misunderstanding of how layers were represented in the graph.

Fix transpose removal

---

coremltools/test/neural_network/test_numpy_nn_layers.py

check if the target shape has dim > 400...

Reshape test case

---

coremltools/converters/nnssa/coreml/ssa_converter.py
coremltools/converters/nnssa/frontend/graph_pass/type_inference.py
coremltools/converters/tensorflow/test/test_tf_2x.py

Support einsum with
1. inner product with arbitrary rank input.
2. transpose with arbitrary rank input.
3. matrix multiplication.
4. batch matrix multiplication with arbitrary rank.

Tf2 add einsum op

---

coremltools/test/neural_network/test_quantization.py

A test that should have been added along with the change in PR #652 
Adding it now.

Quantize test for embedding ND layer

---

coremltools/converters/tensorflow/_tf_converter.py
coremltools/converters/tensorflow/test/test_tf_2x.py

saved_model and Keras model should use different loading methods

fix bug in tf2 convert.

---

.travis.yml

The virtual environment of Python 3.6 installed in travis seems to be creating issues.

Fixing the python-3.6 build

---

coremltools/converters/nnssa/coreml/graph_pass/op_removals.py
coremltools/converters/tensorflow/test/test_tf_2x.py

should fix #623 and internal model conversion bug.

Op not in list bug

---

coremltools/converters/nnssa/frontend/graph_pass/type_inference.py

Previously I used the output_shape attribute in tensorflow ensum to inference the shape,
but it is wrong since if the tensorflow graph have dynamic shape definition but the user gives static input shape the output_shape attribute will still give -1 axis.
Fix one of the negative axis bug for internal model conversion.

fix einsum type inference

---

coremltools/converters/nnssa/commons/builtins/type_spec.py
coremltools/converters/sklearn/_k_neighbors_classifier.py
coremltools/models/_graph_visualization.py
coremltools/models/neural_network/builder.py

Fix deprecation warning regarding invalid escape sequences and comparison of literals.

---

coremltools/converters/sklearn/_imputer.py

A small fix for [#690](https://github.com/apple/coremltools/pull/690)

support scikit-learn >= 0.21: fix for sklearn_class

---

coremltools/converters/mil/frontend/tensorflow/test/test_graphs.py
coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_numerical.py
coremltools/converters/mil/mil/ops/defs/tensor_operation.py
coremltools/converters/mil/mil/ops/tests/test_tensor_operation.py

Also, corrects type inference for non-zero layer.

Handling default value for strides in avg_pool2d and max_pool2d

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_internal_graph.py

Hi,
I had cancelled my old PR https://github.com/apple/coremltools/pull/829 earlier.
This is a new PR with the same content + addresses the code review comments by @DawerG on the old PR.

PyTorch Frontend - add sum, neg and topk ops

---

coremltools/converters/mil/input_types.py

Change error message.

---

coremltools/converters/mil/frontend/torch/internal_graph.py

fix issue #804

---

coremltools/converters/mil/mil/ops/defs/image_resizing.py

in converter.mil.ops.
Includes changes to the docstrings for the following MIL ops:
```
upsample_nearest_neighbor
upsample_bilinear
resize_bilinear
crop_resize
crop
```

Docs: Fix formatting and add ops to image_resizing.py

---

coremltools/converters/mil/mil/ops/defs/image_resizing.py
coremltools/converters/mil/mil/ops/defs/random.py
coremltools/converters/mil/mil/ops/defs/recurrent.py
coremltools/converters/mil/mil/ops/defs/reduction.py
coremltools/converters/mil/mil/ops/defs/scatter_gather.py
coremltools/converters/mil/mil/ops/defs/tensor_operation.py

Update the docstrings in the following docs:
reduction.py
scatter_gather.py
image_resizing.py
tensor_operation.py
recurrent.py
random.py

Docs: Part 1-Update docs in converter.mil.ops

---

coremltools/converters/mil/mil/ops/defs/conv.py
coremltools/converters/mil/mil/ops/defs/elementwise_binary.py
coremltools/converters/mil/mil/ops/defs/elementwise_unary.py
coremltools/converters/mil/mil/ops/defs/pool.py
coremltools/converters/mil/mil/ops/defs/tensor_transformation.py

Update the docstrings in the following docs:
conv.py
elementwise_binary.py
elementwise_unary.py
pool.py
tensor_transformation.py

Docs: Part 2-Update docs in converter.mil.ops

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Enable torch topk op

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Fix torch 1.7.0 conv2d.
Fix interpolation with scaling factor.
Fix lstm test.

Add pytorch group normalization.

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

MIL implementation of pytorch log10

MIL implementation of pytorch log10

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

MIL operations missing from pytorch pad

MIL ops for pytorch pad

---

coremltools/converters/sklearn/_gradient_boosting_regressor.py
coremltools/test/sklearn_tests/test_composite_pipelines.py

Scikit Learn: support huber loss for Gradient Boosted Regressor

---

BUILDING.md
coremltools/test/api/test_api_examples.py
setup.py

Follow up of #1030 . 
I don't honestly know if I'm heading to the correct direction. Feel free to ignore this if there's a grand plan.

Clean up Python 2.7 related content

---

coremltools/converters/mil/backend/nn/op_mapping.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

fix bug in conv_transpose

---

README.md

Changes for the README file that informs the reader of version 5 and provides a simple installation instruction.

Changes to README.md for v5

---

docs/documentation.md

Made editing changes to the process of creating and updating the coremltools [API Reference](https://apple.github.io/coremltools/index.html).

Edited documentation.md in docs

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Support PyTorch Convolution with "same" Padding

---

coremltools/converters/mil/mil/passes/apply_common_pass_pipeline.py
coremltools/converters/mil/mil/passes/test_use_reflection_padding.py
coremltools/converters/mil/mil/passes/use_reflection_padding.py
coremltools/converters/mil/testing_utils.py

Fix Simple Bug in Use Reflection Padding MIL Pass

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Add dot and mv torch ops

---

coremltools/models/neural_network/builder.py

Remove incorrect information from the documentation

---

coremltools/converters/mil/mil/ops/defs/image_resizing.py
coremltools/converters/mil/mil/ops/defs/recurrent.py
coremltools/models/model.py
coremltools/models/neural_network/builder.py

This PR addresses the following doc problems:
* [rdar://90268858](https://rdar.apple.com/problem/90268858) (Fix GRU documentation)
* [rdar://89477261](https://rdar.apple.com/problem/89477261) (Doc str = "TODO" in mil/ops/defs/image_resizing.py)
* Sphinx `UserWarning: potentially wrong underline length`
It includes the following files:
```
coremltools/converters/mil/mil/ops/defs/image_resizing.py # Remove TODO
coremltools/converters/mil/mil/ops/defs/recurrent.py      # GRU fix
coremltools/models/model.py                               # underline
coremltools/models/neural_network/builder.py              # underline
```

GRU Doc edits and TODO removal

---

_modules/coremltools/converters/mil/mil/ops/defs/image_resizing.html
_modules/coremltools/converters/mil/mil/ops/defs/recurrent.html
_modules/coremltools/models/model.html
_modules/coremltools/models/neural_network/builder.html
source/coremltools.converters.mil.mil.ops.defs.html

HTML generated by Sphinx for PR 1445.

HTML Generated for PR 1445

---

coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
coremltools/converters/mil/mil/ops/defs/elementwise_unary.py

Fixes #1418. Also applies that fix to several other similar operations.

Rank zero input numpy tensor

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

https://pytorch.org/docs/stable/generated/torch.triu.html
Resolve #1313

Add triu to PyTorch ops.

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Please merge https://github.com/apple/coremltools/pull/1440 first.
I implemented logical_and and logical_xor for Pytorch.

Support Torch logical and / xor

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Support torch outer ops.

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Fixes #1220 
Also remove some outdated unit test xfails.

Adds full_like torch op

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

torch flatten ops supports flexible input.

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Add global min/max

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

1. Support torch log2 op.
2. Add unit test for log2.

Add torch ops log2

---

.gitlab-ci.yml
coremltools/converters/mil/frontend/milproto/load.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
coremltools/converters/mil/mil/ops/defs/iOS15/tensor_transformation.py
coremltools/converters/mil/mil/passes/compression_passes.py

* GitLab config change:
- fix collection artifacts job dependencies
- Remove Linux
- flake8 and documentation job run on macOS
- change runner tag to macOS12
* Fix issues found by flake8
* xfail a unit test
* Minor clean ups
Green CI run: https://gitlab.com/coremltools1/coremltools/-/pipelines/599584467

Initial Changes for Rebuilt CI

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Fixes: #1433
CI run: https://gitlab.com/coremltools1/coremltools/-/pipelines/622160631

Add clamp_min torch op

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Fixes: #1554
~~CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/624191129~~
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/625753562

new_empty PyTorch op support

---

coremltools/converters/mil/frontend/tensorflow/ops.py
coremltools/converters/mil/frontend/tensorflow/test/test_ops.py

Added Cross tf op and unit test. This allows conversion of models that use `tf.cross`.

Implement cross product tf op.

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Fixes: #1347
CI:
~~https://gitlab.com/coremltools1/coremltools/-/pipelines/658387753~~
~~https://gitlab.com/coremltools1/coremltools/-/pipelines/658447305~~
~~https://gitlab.com/coremltools1/coremltools/-/pipelines/661359144~~
https://gitlab.com/coremltools1/coremltools/-/pipelines/664153138

Support weight_norm torch op

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Torch hann window

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Support torch randint ops.

---

coremltools/converters/mil/mil/passes/name_sanitization_utils.py
coremltools/converters/mil/mil/tests/test_programs.py

fixes https://github.com/apple/coremltools/issues/1634

don't allow "tensor" as the name for a node

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
coremltools/converters/mil/mil/ops/defs/iOS15/elementwise_unary.py

Torch expand op handles dynamic shape

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Support torch cross ops.

---

coremltools/test/xgboost_tests/test_boosted_trees_classifier.py

Unskip unit tests that were skipped as part of #50.
CI run:
https://gitlab.com/coremltools1/coremltools/-/pipelines/675649885

Unskip Unit Tests

---

coremltools/converters/mil/frontend/torch/load.py

Simple bug fix for a recent change (#1640).
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/676997856

Minor Bug Fix

---

coremltools/converters/mil/input_types.py

Minor docstring edit

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Support torch.repeat with dynamic inputs

---

coremltools/converters/mil/frontend/_utils.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Torch einsum eq handles spacing properly.

---

README.md

Badge points to master, not main, which is incorrect.

Build status badge ref=main

---

coremltools/converters/mil/frontend/torch/ops.py

Refactoring torch _pad_packed_sequence.

---

coremltools/converters/mil/frontend/torch/converter.py
coremltools/converters/mil/frontend/torch/internal_graph.py
coremltools/converters/mil/frontend/torch/load.py
coremltools/converters/mil/frontend/torch/test/test_api.py
coremltools/converters/mil/frontend/torch/test/test_examples.py

Fixes: #1504
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/682888839

TorchScript bug fix and clean up

---

.gitlab-ci.yml
coremltools/converters/mil/frontend/tensorflow2/test/test_v2_ops_tf_keras.py

~~CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/681773191~~
~~CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/682662483~~
~~CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/683993684~~
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/684939779

Add TF2 unit tests to CI

---

coremltools/converters/mil/mil/types/__init__.py
coremltools/converters/mil/mil/types/type_dict.py
coremltools/converters/mil/mil/types/type_int.py
coremltools/converters/mil/mil/types/type_list.py
coremltools/converters/mil/mil/types/type_tuple.py

Fixes: #702
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/675690248

Stop overriding Python's built in int type

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Support torch roll ops.

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Support Torch op mish

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Fixes https://github.com/apple/coremltools/issues/1364
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/710030021

[PyTorch] Adds support for torch.nn.unfold (im2col) op in Core ML Tools.

---

coremltools/models/neural_network/quantization_utils.py

Make error message actionable

---

coremltools/converters/mil/backend/nn/op_mapping.py
coremltools/converters/mil/mil/ops/tests/test_slice.py
coremltools/converters/mil/mil/tests/test_block.py
coremltools/models/neural_network/flexible_shape_utils.py

Fixes #1659
~~CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/694295847~~
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/698108240

Fix nerualnetwork backend slice_by_index bug

---

coremltools/converters/mil/backend/mil/load.py
coremltools/converters/mil/frontend/milproto/load.py

Fixes: 1320
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/722686092

Allow coremltools to be imported when installed via an egg

---

_modules/coremltools/converters/mil/mil/ops/defs/iOS15/recurrent.html
source/coremltools.converters.mil.mil.ops.defs.html

This PR is the generated HTML for #1727.
[HTML preview](https://tonybove-apple.github.io/coremltools/index.html)

HTML Generated for Docs - Recurrent API Equation Format

---

coremltools/converters/mil/frontend/torch/converter.py
coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
coremltools/converters/mil/mil/block.py

Fixes: #1767
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/777620760

Add PyTorch op: tupleindex

---

a.patch
coremltools/converters/mil/frontend/_utils.py
coremltools/converters/mil/frontend/tensorflow/test/test_ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Support sum cases for einsum like "ab->a".
Scalar output still is not supported.

Support sum case einsum.

---

coremltools/models/model.py
coremltools/models/utils.py
coremltools/test/api/test_api_visibilities.py
coremltools/test/pipeline/test_pipeline.py

~~CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/807860602~~
~~CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/810485846~~
~~CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/812316099~~
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/813366685
Related to #1773

Initial implementation of make_pipeline utility

---

coremltools/converters/mil/backend/nn/op_mapping.py
coremltools/converters/mil/backend/nn/passes/mlmodel_passes.py
coremltools/converters/mil/frontend/tensorflow/ops.py
coremltools/converters/mil/frontend/tensorflow/tf_graph_pass/visitors.py
coremltools/converters/mil/mil/ops/defs/iOS15/tensor_operation.py
coremltools/converters/mil/mil/passes/defs/quantization.py
coremltools/converters/mil/mil/passes/tests/test_passes.py
coremltools/converters/sklearn/_dict_vectorizer.py
coremltools/models/model.py
coremltools/models/nearest_neighbors/builder.py
coremltools/models/neural_network/builder.py
coremltools/models/neural_network/quantization_utils.py
coremltools/models/neural_network/spec_inspection_utils.py
coremltools/test/neural_network/test_numpy_nn_layers.py
mlmodel/docs/readme_session.py
mlmodel/docs/upload_docs.py

% `ruff --exclude=deps --select=E71,F632 --statistics .`
```
1	E711	[*] Comparison to `None` should be `cond is not None`
7	E712	[*] Comparison to `False` should be `cond is False`
17	E713	[*] Test for membership should be `not in`
2	F632	[*] Use `!=` to compare constant literals
```
% `ruff --exclude=deps --select=E71,F632 --fix .`
```
Found 27 errors (27 fixed, 0 remaining).
```
Related to #687 and #688

Ruff fix some Python code issues

---

coremltools/test/pipeline/test_pipeline.py

CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/844843231

Fix unit test for Linux

---

coremlpython/CoreMLPython.h
coremlpython/CoreMLPython.mm
coremltools/models/model.py
coremltools/test/modelpackage/test_modelpackage.py

Fixes: #196
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/841177689

Batching for MLModel::predict

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

See discussion in #1845, repro in #1848

Ensure shapes passed to `mb.fill` are `int`

---

README.md

Add instructions to install version 7.0b1

---

coremltools/converters/mil/frontend/_utils.py
coremltools/converters/mil/frontend/tensorflow/ops.py
coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
coremltools/converters/mil/mil/ops/defs/_utils.py
coremltools/converters/mil/testing_utils.py

`einsum` can receive one or three or more operand.
This PR make coremltools to handle such a `einsum`.

Support arbitrary number operands einsum.

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
coremltools/converters/mil/frontend/torch/torchir_passes.py

Resolves #1872 
Related to #1861
With this change, I succeeded to fixed shape . (but not with flexible shape)
```python
import torch
import numpy as np
from transformers import AutoModel, AutoProcessor, OwlViTForObjectDetection
from PIL import Image
import requests
class MyOpenDetector(torch.nn.Module):
def __init__(self, model=None):
super(MyOpenDetector, self).__init__()
self.model = model
def forward(self, input_ids, pixel_values, attention_mask):
return self.model(input_ids=input_ids, pixel_values=pixel_values, attention_mask=attention_mask)
def save_owlvitmodel(inputs, modelname):
openModel = OwlViTForObjectDetection.from_pretrained(modelname, torchscript=True).eval()
x = tuple([inputs['input_ids'], inputs['pixel_values'], inputs['attention_mask']])
model = …
```

Fix torch fill_.

---

coremltools/models/neural_network/builder.py

Fix docstring example code

---

coremltools/converters/mil/frontend/tensorflow/ops.py

In Core ML, all resizing-related ops requires compile-time-determined size-related input, either const `output shape` (e.g. [resize_nearest_neighbor](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#coremltools.converters.mil.mil.ops.defs.iOS15.image_resizing.resize_nearest_neighbor)) or const `output shape / input shape` ratio (e.g. [upsample_bilinear](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#coremltools.converters.mil.mil.ops.defs.iOS15.image_resizing.upsample_bilinear)).
Concretely, the only dynamic-input-shape image resizing that can be converted to CoreML is something like `output shape = input shape * 1.5`, i.e. although the `input shape` is dynamic, the scaling factor is constant. Otherwise, …

clearer error message for dynamic input shape tf.raw_ops.ResizeNearestNeighbor

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

With this change I confirmed #1861 was fixed.
Also related to #1788

Support flexible shape fill_ for torch.

---

.gitignore
coremltools/converters/mil/input_types.py
coremltools/models/utils.py

* Add `__str__` magic method to size class. This will help debug issues like #1338.
* Minor doctoring clean ups.
* Git ignore tilda files.

Minor fix ups

---

coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
coremltools/converters/mil/mil/ops/defs/iOS15/elementwise_unary.py
coremltools/converters/mil/mil/types/type_tensor.py

Value inference for log: output shape should match input shape

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Supports PyTorch view_as_real op, along with test cases.
Fixes https://github.com/apple/coremltools/issues/1929

Supports PyTorch view_as_real op.

---

coremltools/converters/mil/frontend/torch/ops.py

Fixes #1967
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1000316143

PyTorch masked_fill promote dtype

---

docs-guides/source/performance-impact.html
docs-guides/source/quantization-overview.html

These are the doc changes corresponding to #1987 
See the link in that PR for previews.

[Documentation] Update perf numbers for compression models with ios17

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Fixes: #1973
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1005041699

Fix torch randint issue

---

coremltools/converters/_converters_entry.py
coremltools/models/model.py
coremltools/models/utils.py
coremltools/test/pipeline/test_pipeline.py

CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1018956535

Add compute_units parameter to ct.utils.make_pipeline

---

coremltools/models/utils.py
coremltools/test/pipeline/test_pipeline.py

Better logic for determining inputs/outputs of pipelines.
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1024597996

Bug Fix: ct.models.utils.make_pipeline

---

coremltools/converters/mil/mil/ops/defs/iOS15/control_flow.py

Remove incorrect information from docstring

---

coremltools/converters/mil/mil/ops/defs/iOS15/image_resizing.py
coremltools/converters/mil/mil/ops/defs/iOS17/image_resizing.py
coremltools/converters/mil/mil/ops/tests/iOS15/test_image_resizing.py
coremltools/converters/mil/mil/ops/tests/iOS17/test_image_resizing.py

Fix issue #2038 
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1058433443

fix typo for crop_size default value

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Fixes: #1409
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1050885804

PyTorch: 1D adaptive pooling (max & avg)

---

coremltools/converters/mil/input_types.py
coremltools/converters/mil/mil/ops/defs/iOS15/linear.py

CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1046838784

Minor enhancements

---

coremltools/converters/mil/frontend/tensorflow/test/test_ops.py

CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1075644464

Skip Some TF1 NMS unit tests on macOS 14

---

docs-guides/source/installing-coremltools.md
docs-guides/source/new-features.md

This PR updates the supported Python versions on the [Installing Core ML Tools](https://apple.github.io/coremltools/docs-guides/source/installing-coremltools.html) and [New Features](https://apple.github.io/coremltools/docs-guides/source/new-features.html) pages.
---
**Preview**:
- [Core ML Tools Guide](https://tonybove-apple.github.io/coremltools/docs-guides/)

Docs-Guides - Update Supported Python Versions

---

mlmodel/docs/Format/DataStructures.rst
mlmodel/docs/Format/FeatureTypes.rst
mlmodel/docs/Format/Model.rst
mlmodel/docs/Format/Parameters.rst

This PR updates [Core ML Model Format Specification](https://apple.github.io/coremltools/mlmodel/index.html) pages; specifically:
- [Core ML Model](https://apple.github.io/coremltools/mlmodel/Format/Model.html)
- [DataStructures](https://apple.github.io/coremltools/mlmodel/Format/DataStructures.html)
- [FeatureTypes](https://apple.github.io/coremltools/mlmodel/Format/FeatureTypes.html)
- [Parameters](https://apple.github.io/coremltools/mlmodel/Format/Parameters.html)
**Preview**:
- [Core ML Model Format Specification](https://tonybove-apple.github.io/coremltools/mlmodel/)

Mlmodel Docs - Update Proto Pages Batch 1

---

coremltools/converters/_converters_entry.py
coremltools/converters/mil/frontend/torch/load.py

Fixes: #1228
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1156785858

Prevent multiple loads of PyTorch and better error message

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/mil/builder.py

CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1171431348

Minor Fixes

---

docs-guides/source/new-features.md

Remove one "the" from "the the"

Fix typo in new-features.md

---

coremltools/converters/_converters_entry.py

Fix typo in error message for minimum_deployment_target

---

coremltools/version.py

✅ [CI](https://gitlab.com/coremltools1/coremltools/-/commit/7c13259578e8ca0511aa7423a57718a3c7f192b4)

Bump Version to 7.2.1

---

coremltools/converters/_profile_utils.py

Changed string's format to f-string. Code became more clear and also we avoid potential type's mismatch.

Changed string's format to f-string. 

---

coremltools/converters/mil/frontend/torch/ops.py

Clip is just an alias to clamp

Add clip op

---

docs/source/coremltools.optimize.torch.pruning.rst
docs/source/coremltools.optimize.torch.quantization.rst

A couple of APIs got missed in the previous PR (#2233). This PR adds those.

[Doc] Add missing api reference for 8.0b1

---

docs-guides/source/opt-quantization-overview.md
docs-guides/source/opt-quantization-perf.md

Updating the text to more accurately reflect our shipping product names.

Device name updates

---

.gitignore
docs-guides/source/stateful-models.html

HTML updates for https://github.com/apple/coremltools/pull/2289
Preview: https://junpeiz.github.io/coremltools/docs-guides/source/stateful-models.html#example-toy-attention-model-with-stateful-kv-cache

[Docs] HTML updates for stateful kv-cache models.

---

README.md

Correct wording from `lastest` to `latest`.

Fix typo issue at README.md

---

coremltools/converters/mil/input_types.py
coremltools/models/model.py
coremltools/models/utils.py
coremltools/optimize/torch/palettization/palettization_config.py
coremltools/optimize/torch/palettization/post_training_palettization.py
coremltools/optimize/torch/palettization/sensitive_k_means.py

This PR reviews and makes edits to 10 of the 17 new docstrings in the Core ML Tools public API reference guide
- Fix typos, ill-formatted links, and prose that did not match Apple style
- Normalize spelling of "lookup table" and "k-means operation" in non-code text
- Make description and arguments of ModuleSKMPalettizerConfig and ModulePostTrainingPalettizerConfig be the same, per Nehal Bhandari's guidance
2 docstrings related to the state feature:
- StateType: https://apple.github.io/coremltools/source/coremltools.converters.mil.input_types.html#coremltools.converters.mil.input_types.StateType , 
- make_state API: https://apple.github.io/coremltools/source/coremltools.models.html#coremltools.models.model.MLModel.make_state
2 docstrings related to the multiple function feature
- …

Review of new Core ML Tools public API docstrings, part 1

---

coremltools/optimize/torch/_utils/graph_utils.py
coremltools/optimize/torch/_utils/transforms.py

Guarding imports if the relevant packages are not installed in the environment. 
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1434167651
~CI: https://gitlab.com/coremltools1/coremltools/-/commit/63ae12e7b4cb8725b7bd43b9b2b5959425f60f2a~

Fixing imports to not require torchvision installed

---

coremltools/converters/mil/frontend/torch/ops.py

CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1434285067

Fix error message generation for top level PyTorch ops

---

coremltools/converters/mil/mil/ops/defs/iOS18/recurrent.py

Update iOS18 GRU Docstring

---

README.md

CI - https://gitlab.com/coremltools1/coremltools/-/pipelines/1553357124
Update README for version 8.1

Update README for version 8.1

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Support some new ops translation from torch.export
1. nan_to_num
2. cumprod
3. searchsorted
4. one_hot
Testing: https://gitlab.com/coremltools1/coremltools/-/commit/a11386ea8a62eae1062861205e82e5a5ff809364/pipelines

[Torch.Export] Support Some New Ops Translation

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Support some final important ops translation from torch.export
1. squeeze
2. var & std
3. topk
4. amax & amin
5. glu
6. nonzero
7. argmax
8. stack
9. scatter
Testing:
~~❌ https://gitlab.com/coremltools1/coremltools/-/commit/d169d98d6b9e287135c590a011c028046f9f1534/pipelines~~
✅ https://gitlab.com/coremltools1/coremltools/-/commit/676e7fde6eac9759abf1bd47d5d080a200002c3e/pipelines

[Torch.Export] Support Some Final Important Ops Translation

---

coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

Support factory ops translation from torch.export
1. zeros
2. full
3. new zeros
4. new full
Testing: ✅ https://gitlab.com/coremltools1/coremltools/-/commit/f1526dee31f0f4f827c45063fbe9153805c53f4d/pipelines

[Torch.Export] Support Factory Ops Translation

---

reqs/test.pip

CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1613455322

Pin peft Dependency Version

---

coremltools/models/compute_plan.py

fix: correct typos in comments

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

add argmin support for model lowering

add argmin support

---

coremltools/converters/mil/frontend/torch/ops.py

Adds alias for power pow.tensor_tensor

Add alias for pow

---

coremlpython/CoreMLPython.mm
coremltools/models/_compiled_model.py
coremltools/models/model.py
coremltools/test/modelpackage/test_modelpackage.py
coremltools/test/neural_network/test_compiled_model.py

Adds allowLowPrecisionAccumulationOnGPU optimization hint to MLModel and CompiledMLModel.
CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1796255305

Allow Low Precision Accumulation On GPU 

---

docs-guides/source/mlmodel-debugging-perf-utilities.md

Add `Experimental` admonition for API usage
https://cymbalrush.github.io/coremltools/docs-guides/source/mlmodel-debugging-perf-utilities.html

Add `Experimental` admonition

---

docs-guides/source/mlmodel-debugging-perf-utilities.md

Fix import in Debugging And Perf Utilities guide
https://cymbalrush.github.io/coremltools/docs-guides/source/mlmodel-debugging-perf-utilities.html

Fix import in Debugging And Perf Utilities guide

---

coremltools/converters/_converters_entry.py
coremltools/converters/mil/frontend/torch/test/test_torch_conversion_api.py
coremltools/models/__init__.py
coremltools/models/model.py

CI: https://gitlab.com/coremltools1/coremltools/-/pipelines/1834087623

Adds conversion date to model meta data.

---

coremltools/converters/mil/frontend/torch/ops.py
coremltools/converters/mil/frontend/torch/test/test_torch_ops.py

This PR replaces the gather operation with a more efficient conv2d-based implementation for the im2col operation. 
The new implementation:
1. Support `dilation` parameters.
2. Handle dynamic height/width in [N, C, H, W] tensors. (Addressing a limitation reported in #2446)
3. Provide better performance compared to the previous implementation.
The performance report for an input tensor of shape [1, 3, 128, 128]:
- Before:
- After:

Optimize torch im2col implementation

---

coremltools/converters/mil/mil/operation.py
coremltools/converters/mil/mil/tests/test_programs.py

Fixes #2530.
Added new check for const op type that fills the real/imag data of the ComplexVar.
Added a unit test.

Fix complex const initialization (fixes #2530)
